GoogleCloudDataproc/spark-bigquery-connector

CHANGES.md, README.md, build.sbt, examples/python/shakespeare.py, src/main/scala/com/google/cloud/spark/bigquery/SchemaConverters.scala, src/main/scala/com/google/cloud/spark/bigquery/examples/Shakespeare.scala, src/test/scala/com/google/cloud/spark/bigquery/SchemaConvertersSuite.scala, src/test/scala/com/google/cloud/spark/bigquery/it/IntegrationTestUtils.scala, src/test/scala/com/google/cloud/spark/bigquery/it/SparkBigQueryEndToEndITSuite.scala, src/test/scala/com/google/cloud/spark/bigquery/it/TestConstants.scala
Also clean up reliance on non-public pre-created tables in integration
tests and examples.
=> Add support for NUMERIC types

cloudbuild/Dockerfile, cloudbuild/cloudbuild.yaml, project/build.properties
Upgrade sbt version to workaround problem described in: https://github.com/sbt/sbt-launcher-package/pull/158/files
=> Setup presubmit and post merge tests using cloud build

.gitignore, CHANGES.md, README.md, build.sbt, src/main/scala/com/google/cloud/spark/bigquery/BigQueryInsertableRelation.scala, src/main/scala/com/google/cloud/spark/bigquery/BigQueryRelation.scala, src/main/scala/com/google/cloud/spark/bigquery/BigQueryRelationProvider.scala, src/main/scala/com/google/cloud/spark/bigquery/BigQueryWriteHelper.scala, src/main/scala/com/google/cloud/spark/bigquery/SparkBigQueryOptions.scala, src/main/scala/com/google/cloud/spark/bigquery/direct/BigQueryRDD.scala, src/test/scala/com/google/cloud/spark/bigquery/it/SparkBigQueryEndToEndITSuite.scala
This PR adds DataFrame-to-BigQuery write support. In addition, it adds a Scala 2.11 and 2.12 cross build artifacts.
=> Adding write support

src/main/java/com/google/cloud/spark/bigquery/examples/JavaShakespeare.java, src/main/scala/com/google/cloud/spark/bigquery/BigQueryRelationProvider.scala
The answer the question on StackOverflow (https://stackoverflow.com/questions/58668507/how-to-read-from-bigquery-into-apache-spark-using-java)
=> Adding Java Example

src/main/scala/com/google/cloud/spark/bigquery/BigQueryRelationProvider.scala, src/main/scala/com/google/cloud/spark/bigquery/SparkBigQueryOptions.scala, src/test/scala/com/google/cloud/spark/bigquery/BigQueryRelationProviderSuite.scala
#6 do not initialize bigquery options by default
#23 added test ensuring that credentials option is used
=> #6 do not initialize bigquery options

build.sbt, src/main/scala/com/google/cloud/spark/bigquery/BigQueryUtil.scala, src/main/scala/com/google/cloud/spark/bigquery/SchemaConverters.scala, src/main/scala/com/google/cloud/spark/bigquery/SparkBigQueryOptions.scala, src/main/scala/com/google/cloud/spark/bigquery/direct/BigQueryRDD.scala, src/test/java/com/google/cloud/spark/bigquery/MockResponsesBatch.java, src/test/scala/com/google/cloud/spark/bigquery/BigQueryRelationProviderSuite.scala, src/test/scala/com/google/cloud/spark/bigquery/DirectBigQueryRelationSuite.scala, src/test/scala/com/google/cloud/spark/bigquery/ReadRowsSuite.scala
1. Related to https://issuetracker.google.com/issues/143292803, based on @kmjung request
2. Issue #97 Adding support for geography type
=> Adding retries for GRPC issues, support geography type

src/main/scala/com/google/cloud/spark/bigquery/BigQueryRelationProvider.scala, src/main/scala/com/google/cloud/spark/bigquery/BigQueryWriteHelper.scala, src/main/scala/com/google/cloud/spark/bigquery/SparkBigQueryOptions.scala
Fixing multiple potential match errors and a bug in option extraction.
=> Initial commit on Datadrivers fork

build.sbt, connector/src/main/scala/com/google/cloud/spark/bigquery/BigQueryInsertableRelation.scala, connector/src/main/scala/com/google/cloud/spark/bigquery/BigQueryRelation.scala, connector/src/main/scala/com/google/cloud/spark/bigquery/BigQueryWriteHelper.scala, connector/src/main/scala/com/google/cloud/spark/bigquery/SchemaConverters.scala, connector/src/main/scala/com/google/cloud/spark/bigquery/direct/BigQueryRDD.scala, connector/src/main/scala/com/google/cloud/spark/bigquery/direct/DirectBigQueryRelation.scala, connector/src/test/scala/com/google/cloud/spark/bigquery/it/IntegrationTestUtils.scala, connector/src/test/scala/com/google/cloud/spark/bigquery/it/SparkBigQueryEndToEndITSuite.scala
- Scalastyle issues
- Removing scala-logging due to dependency issues on Databricks runtime.
=> General cleanups

connector/src/main/scala/com/google/cloud/spark/bigquery/SchemaConverters.scala, connector/src/test/scala/com/google/cloud/spark/bigquery/SchemaConvertersSuite.scala, connector/src/test/scala/com/google/cloud/spark/bigquery/it/SparkBigQueryEndToEndITSuite.scala
Adding the field description from BigQuery to the DataFrame schema metadata
=> Issue #130 Adding the field description to the schema metadata

connector/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConnectorUserAgentProvider.java
=> Fixing SparkBigQueryConnectorUserAgentProvider initialization bug

build.sbt, connector/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryCredentialsSupplier.java, connector/src/test/java/com/google/cloud/spark/bigquery/v2/BigQueryInputPartitionReaderTest.java, published/src/test/java/com/google/spark/bigquery/acceptance/AcceptanceTestContext.java, published/src/test/java/com/google/spark/bigquery/acceptance/AcceptanceTestUtils.java, published/src/test/java/com/google/spark/bigquery/acceptance/DataprocAcceptanceTestBase.java, published/src/test/java/com/google/spark/bigquery/acceptance/DataprocImage13AcceptanceTest.java, published/src/test/java/com/google/spark/bigquery/acceptance/DataprocImage14AcceptanceTest.java, published/src/test/java/com/google/spark/bigquery/acceptance/DataprocImage15AcceptanceTest.java, published/src/test/resources/acceptance/read_shakespeare.py
In order to run the test:
```
sbt package acceptance:test
```
=> Adding acceptance test on Dataproc

README.md, connector/src/main/scala/com/google/cloud/spark/bigquery/BigQueryWriteHelper.scala, connector/src/main/scala/com/google/cloud/spark/bigquery/SparkBigQueryOptions.scala, connector/src/test/scala/com/google/cloud/spark/bigquery/SparkBigQueryOptionsSuite.scala
I would like do make import to BQ and keep the data in GCS.
Issue: #195
=> Keep GCS data after import to BigQuery

README.md
Updating readme to include streaming writes. 
Minor typo fix
=> Update streaming write doc

connector/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClientModule.java, connector/src/main/java/com/google/cloud/bigquery/connector/common/ReadRowsHelper.java
- Adds try catch branch to avoid race condition
- Makes the module to use explicit in BigqueryClientModule
(I needed this for compilation due to ambiguity with
java.lang.Module)
=> Add try catch branch around cancel.

cloudbuild/cloudbuild.yaml, connector/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryCredentialsSupplier.java, connector/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryUtil.java, connector/src/test/java/com/google/cloud/bigquery/connector/common/BigQueryCredentialsSupplierTest.java, connector/src/test/java/com/google/cloud/bigquery/connector/common/BigQueryUtilTest.java
It appears that the previous code that had relied on Java streams had issues, reverting to simpler code structure, added additional tests.
=> Code simplification to solve Issue #249

connector/src/main/scala/com/google/cloud/spark/bigquery/BigQueryUtil.scala
Remove unnecessary string interpolation character, it seems to be a typo
=> String interpolation typo

connector/src/main/java/com/google/cloud/spark/bigquery/v2/BigQueryDataSourceReader.java, connector/src/main/scala/com/google/cloud/spark/bigquery/direct/DirectBigQueryRelation.scala
Based on conversation with @emkornfield
=> Bumping the log severity from debug in case of an optimized count() run

connector/src/main/java/com/google/cloud/spark/bigquery/examples/JavaShakespeare.java
Modified JavaShakespeare.java to incorporate parameters for input/output/temporary GCS buckets
=> Parameterised shakespeare example

connector/src/test/scala/com/google/cloud/spark/bigquery/SchemaIteratorSuite.scala
=> Fix minor typo in test

cloudbuild/cloudbuild.yaml, connector/src/test/scala/com/google/cloud/spark/bigquery/it/SparkBigQueryEndToEndWriteITSuite.scala
=> Issue #348: temporaryGcsBucket is now set externally to the code

connector/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClient.java
=> Misc refactor

connector/src/main/java/com/google/cloud/bigquery/connector/common/LoggingBigQueryStorageReadRowsTracer.java
The spark time includes all time spent inside the method parsing data so we need to subtract that component out to understand how much time is spent outside of tha tmethod.
=> Correct display of spark time.

build.sbt, connector/src/main/java/com/google/cloud/spark/bigquery/ArrowBinaryIterator.java, connector/src/main/java/com/google/cloud/spark/bigquery/v2/ArrowColumnBatchPartitionReader.java
Also adds ability to decompress compressed streams.
=> Upgrade to Arrow 4

build.sbt
Its not clear to me if this is the correct thing to do in all cases, so I'm OK to revert.
=> Force java version to 1.8 and check to ensure 1.8 is used

connector/src/main/java/com/google/cloud/bigquery/connector/common/ReadSessionCreator.java, connector/src/main/scala/com/google/cloud/spark/bigquery/direct/DirectBigQueryRelation.scala, connector/src/test/scala/com/google/cloud/spark/bigquery/it/IntegrationTestUtils.scala, connector/src/test/scala/com/google/cloud/spark/bigquery/it/SparkBigQueryEndToEndReadITSuite.scala
…olumns in select() and flter().
=> Issue #354: users can query a view with different columns in select() and filter()

connector/src/main/java/com/google/cloud/spark/bigquery/SparkFilterUtils.java, connector/src/test/java/com/google/cloud/spark/bigquery/SparkFilterUtilsTest.java
It is more complex then necessary.
=> Don't use unnest syntax for IN

connector/src/main/java/com/google/cloud/bigquery/connector/common/IteratorMultiplexer.java, connector/src/test/java/com/google/cloud/bigquery/connector/common/IteratorMultiplexerTest.java
This will be used in conjunction with the parallel reader in my other PR.
=> Add iterator multiplexer

connector/src/main/java/com/google/cloud/bigquery/connector/common/ReadSessionCreator.java, connector/src/test/java/com/google/cloud/bigquery/connector/common/ReadSessionCreatorTest.java
=> Add back column projection to DSv2

connector/src/main/java/com/google/cloud/spark/bigquery/v2/ArrowColumnBatchPartitionReader.java, connector/src/main/java/com/google/cloud/spark/bigquery/v2/BigQueryDataSourceReader.java, connector/src/main/java/com/google/cloud/spark/bigquery/v2/BigQueryDataSourceReaderModule.java
* Add logging to DSv2 at session creation time.
* Ensure multiplexced tracers log by adding them to the closable list.
=> Fine tune logging:

connector/src/main/java/com/google/cloud/bigquery/connector/common/IteratorMultiplexer.java, connector/src/main/java/com/google/cloud/bigquery/connector/common/ParallelArrowReader.java
If a throwable error is made (for instance ZSTD error) previously this would result in a hang because it wasn't caught and handled in the submitted task.  This PR make changes to catch throwables everyplace necessary to avoid issues like this in the future.
=> Make background processing classes more robust to errors

build.sbt
This required me to update grpcVersion as well.
=> Update google-cloud-bigquerystorage dependency to 2.1.2 in branch-0.22

README.md, bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/ReadSessionCreator.java, bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/ReadSessionCreatorConfig.java, bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/ReadSessionCreatorConfigBuilder.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConfig.java, spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/SparkBigQueryConfigTest.java, spark-bigquery-tests/src/main/java/com/google/cloud/spark/bigquery/integration/ReadIntegrationTestBase.java
=> Added configuration option to use compression from the READ API for Arrow

bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryUtil.java, bigquery-connector-common/src/test/java/com/google/cloud/bigquery/connector/common/BigQueryUtilTest.java, spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/v2/context/BigQueryDirectDataSourceWriterContext.java
=> Treating Field.mode==null as Nullable 

README.md
Updated readme from issue #512 
Also I noticed that readme is missing information added in #267 so I updated it as well
=> update readme with possible partitions type

README.md
=> Update documentation for BigNumeric support in Jupyter Notebooks

spark-bigquery-dsv1/src/main/scala/com/google/cloud/spark/bigquery/BigQueryConnectorUtils.scala, spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/BigQueryPlan.scala, spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/BigQueryStrategy.scala, spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/SparkBigQueryPushdown.scala, spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/SparkBigQueryPushdownUtil.scala, spark-bigquery-pushdown/spark-2.4-bigquery-pushdown_2.11/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark24BigQueryPushdown.scala, spark-bigquery-pushdown/spark-2.4-bigquery-pushdown_2.12/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark24BigQueryPushdown.scala, spark-bigquery-pushdown/spark-3.1-bigquery-pushdown_2.12/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark31BigQueryPushdown.scala
Last bit of integration with dsv1 connector before adding actual functionality in the pushdown modules
=> Added SparkBigQueryPushdownUtil to enable/disable pushdown strategy

bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClient.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConfig.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryUtil.java, spark-bigquery-dsv1/src/main/scala/com/google/cloud/spark/bigquery/BigQueryWriteHelper.scala, spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/v2/context/BigQueryIndirectDataSourceWriterContext.java
The BigQuery load job invocation has moved to BigQueryClient
=> Consolidating the indirect write to a single implementation

spark-bigquery-parent/pom.xml
Skip the the deploy-maven-plugin.  Use the release profile to deploy
using the nexus-staging-maven-plugin.
=> Disable deployments from the default profile.

spark-bigquery-dsv1/src/main/scala/com/google/cloud/spark/bigquery/BigQueryConnectorUtils.scala, spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/BigQueryStrategy.scala, spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/SparkBigQueryPushdown.scala, spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/SparkExpressionConverter.scala, spark-bigquery-pushdown/pushdown_common_src/test/scala/com/google/cloud/spark/bigquery/pushdowns/SparkExpressionConverterSuite.scala, spark-bigquery-pushdown/spark-2.4-bigquery-pushdown_2.11/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark24BigQueryPushdown.scala, spark-bigquery-pushdown/spark-2.4-bigquery-pushdown_2.11/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark24ExpressionConverter.scala, spark-bigquery-pushdown/spark-2.4-bigquery-pushdown_2.12/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark24BigQueryPushdown.scala, spark-bigquery-pushdown/spark-2.4-bigquery-pushdown_2.12/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark24ExpressionConverter.scala, spark-bigquery-pushdown/spark-3.1-bigquery-pushdown_2.12/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark31BigQueryPushdown.scala, spark-bigquery-pushdown/spark-3.1-bigquery-pushdown_2.12/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark31ExpressionConverter.scala
=> Implement converter from Spark expressions to SQL and inject it into BigQueryStrategy

spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/SparkExpressionConverter.scala, spark-bigquery-pushdown/pushdown_common_src/test/scala/com/google/cloud/spark/bigquery/pushdowns/SparkExpressionConverterSuite.scala
Added a whole lot of unit tests for SparkExpressionConverter which was merged in PR #589
=> Added unit tests for SparkExpressionConverter

CHANGES.md, README-template.md
During a release, automation will create two commits.
The release commit will
* replace the ## Next header in CHANGES.md with the release version and date
* remove the ## Unreleased Changes section from README.md
* replace ${next-release-tag} in README.md with the release version
The next development commit will
* Add the ## Next section to CHANGES.md
* Replace the release README.md with the development README.md containing the ## Unreleased Changes section and ${next-release-tag} template.
* Update the link to the latest release in the README.md to point to the current release version.
=> Update CHANGES.md and README.md to capture the next release's info

spark-bigquery-dsv2/spark-3.1-bigquery/src/test/java/com/google/cloud/spark/bigquery/integration/Spark31ReadIntegrationTest.java
Ran spotless apply because mvn clean install was failing
=> Run spotless apply

bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClient.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/direct/BigQueryRDDFactory.java, spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/BigQueryStrategy.scala, spark-bigquery-pushdown/pushdown_common_src/test/scala/com/google/cloud/spark/bigquery/pushdowns/BigQueryStrategySuite.scala
Encountered a few things while testing that need fixing
=> Add minor fixes encountered during testing

spark-bigquery-dsv1/src/test/java/com/google/cloud/spark/bigquery/integration/DatasourceV1QueryPushdownIntegrationTest.java, spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/SparkExpressionConverter.scala, spark-bigquery-pushdown/pushdown_common_src/test/scala/com/google/cloud/spark/bigquery/pushdowns/SparkExpressionConverterSuite.scala, spark-bigquery-tests/src/main/java/com/google/cloud/spark/bigquery/integration/QueryPushdownIntegrationTestBase.java, spark-bigquery-tests/src/main/java/com/google/cloud/spark/bigquery/integration/ReadIntegrationTestBase.java
These are the initial changes for supporting string functions in query pushdown with unit tests
=> initial changes for supporting string functions in query pushdown

cloudbuild/nightly.sh, cloudbuild/nightly.yaml, spark-bigquery-parent/pom.xml, spark-bigquery-tests/src/main/java/com/google/cloud/spark/bigquery/acceptance/BigNumericDataprocServerlessAcceptanceTestBase.java, spark-bigquery-tests/src/main/java/com/google/cloud/spark/bigquery/acceptance/DataprocAcceptanceTestBase.java, spark-bigquery-tests/src/main/java/com/google/cloud/spark/bigquery/acceptance/ReadSheakspeareDataprocServerlessAcceptanceTestBase.java, spark-bigquery-tests/src/main/java/com/google/cloud/spark/bigquery/acceptance/WriteStreamDataprocServerlessAcceptanceTestBase.java
Changing the gax version and fixing acceptance tests for nightly build to run
=> Nightly build failure fix

spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/SparkExpressionConverter.scala, spark-bigquery-pushdown/pushdown_common_src/test/scala/com/google/cloud/spark/bigquery/pushdowns/SparkExpressionConverterSuite.scala, spark-bigquery-tests/src/main/java/com/google/cloud/spark/bigquery/integration/QueryPushdownIntegrationTestBase.java
changes to support mathematical function expressions during query pushdown
Added unit tests and integration tests
=> changes to support mathematical function expressions during query pushdown

spark-bigquery-connector-common/pom.xml, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/AvroIntermediateRecordWriter.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/BigQueryDataSourceWriterModule.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/BigQueryDirectDataSourceWriterContext.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/BigQueryDirectDataWriterContext.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/BigQueryDirectDataWriterContextFactory.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/BigQueryDirectWriterCommitMessageContext.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/BigQueryIndirectDataSourceWriterContext.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/BigQueryIndirectDataWriterContext.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/BigQueryIndirectDataWriterContextFactory.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/BigQueryIndirectWriterCommitMessageContext.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/DataSourceWriterContext.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/DataWriterContext.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/DataWriterContextFactory.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/IntermediateRecordWriter.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/NoOpDataWriterContext.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/WriterCommitMessageContext.java, spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/write/context/BigQueryDirectDataSourceWriterContextTest.java, spark-bigquery-dsv2/spark-2.4-bigquery/src/main/java/com/google/cloud/spark/bigquery/v2/BigQueryDataSourceV2.java, spark-bigquery-dsv2/spark-2.4-bigquery/src/main/java/com/google/cloud/spark/bigquery/v2/BigQueryDataSourceWriter.java, spark-bigquery-dsv2/spark-2.4-bigquery/src/main/java/com/google/cloud/spark/bigquery/v2/Spark24DataWriter.java, spark-bigquery-dsv2/spark-2.4-bigquery/src/main/java/com/google/cloud/spark/bigquery/v2/Spark24DataWriterFactory.java, spark-bigquery-dsv2/spark-2.4-bigquery/src/main/java/com/google/cloud/spark/bigquery/v2/Spark24WriterCommitMessage.java, spark-bigquery-dsv2/spark-3.1-bigquery/src/main/java/com/google/cloud/spark/bigquery/v2/BigQueryBatchWrite.java, spark-bigquery-dsv2/spark-3.1-bigquery/src/main/java/com/google/cloud/spark/bigquery/v2/BigQueryWriteBuilder.java, spark-bigquery-dsv2/spark-3.1-bigquery/src/main/java/com/google/cloud/spark/bigquery/v2/Spark31BigQueryDataWriter.java, spark-bigquery-dsv2/spark-3.1-bigquery/src/main/java/com/google/cloud/spark/bigquery/v2/Spark31BigQueryDataWriterFactory.java, spark-bigquery-dsv2/spark-3.1-bigquery/src/main/java/com/google/cloud/spark/bigquery/v2/Spark31BigQueryWriterCommitMessage.java, spark-bigquery-dsv2/spark-bigquery-dsv2-common/pom.xml
A refactoring commit, no code changes
=> Moving the writer context files to spark-bigquery-connector-common

README.md
Add useAvroLogicalTypes to documented options list, with reference to issue faced in #612.
=> Document useAvroLogicalTypes

spark-bigquery-dsv1/src/test/java/com/google/cloud/spark/bigquery/integration/DataSourceV1QueryPushdownIntegrationTest.java, spark-bigquery-dsv2/spark-2.4-bigquery/src/test/java/com/google/cloud/spark/bigquery/integration/Spark24QueryPushdownIntegrationTest.java, spark-bigquery-dsv2/spark-3.1-bigquery/src/test/java/com/google/cloud/spark/bigquery/integration/Spark31QueryPushdownIntegrationTest.java, spark-bigquery-tests/src/main/java/com/google/cloud/spark/bigquery/integration/QueryPushdownIntegrationTestBase.java, spark-bigquery-tests/src/main/java/com/google/cloud/spark/bigquery/integration/TestConstants.java
This reverts commit 4d212fa3179e663bf046407f781205cac88a7c41.
=> Revert "adding integration tests for join in pushdown (#740)"

spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/BaseSparkBigQueryPushdown.scala, spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/SparkBigQueryPushdownUtil.scala, spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/SparkExpressionConverter.scala, spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/SparkPlanFactory.scala, spark-bigquery-pushdown/pushdown_common_src/test/scala/com/google/cloud/spark/bigquery/pushdowns/TestConstants.scala, spark-bigquery-pushdown/spark-2.4-bigquery-pushdown_2.11/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark24BigQueryPushdown.scala, spark-bigquery-pushdown/spark-2.4-bigquery-pushdown_2.11/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark24BigQueryPushdownPlan.scala, spark-bigquery-pushdown/spark-2.4-bigquery-pushdown_2.11/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark24ExpressionConverter.scala, spark-bigquery-pushdown/spark-2.4-bigquery-pushdown_2.11/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark24PlanFactory.scala, spark-bigquery-pushdown/spark-2.4-bigquery-pushdown_2.12/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark24BigQueryPushdown.scala, spark-bigquery-pushdown/spark-2.4-bigquery-pushdown_2.12/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark24BigQueryPushdownPlan.scala, spark-bigquery-pushdown/spark-2.4-bigquery-pushdown_2.12/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark24ExpressionConverter.scala, spark-bigquery-pushdown/spark-2.4-bigquery-pushdown_2.12/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark24PlanFactory.scala, spark-bigquery-pushdown/spark-3.1-bigquery-pushdown_2.12/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark31BigQueryPushdown.scala, spark-bigquery-pushdown/spark-3.1-bigquery-pushdown_2.12/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark31BigQueryPushdownPlan.scala, spark-bigquery-pushdown/spark-3.1-bigquery-pushdown_2.12/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark31ExpressionConverter.scala, spark-bigquery-pushdown/spark-3.1-bigquery-pushdown_2.12/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark31PlanFactory.scala
Co-authored-by: Vinay Londhe <vinaylondhe@google.com>
=> Adding Scala 2.13 support part 0 - updating pushdown implementation

spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryUtil.java, spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/BigQueryStrategy.scala, spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/SparkBigQueryPushdownUtil.scala, spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/SparkPlanFactory.scala, spark-bigquery-pushdown/pushdown_common_src/test/scala/com/google/cloud/spark/bigquery/pushdowns/BigQueryStrategySuite.scala, spark-bigquery-pushdown/pushdown_common_src/test/scala/com/google/cloud/spark/bigquery/pushdowns/SparkBigQueryPushdownUtilSuite.scala, spark-bigquery-pushdown/spark-2.4-bigquery-pushdown_2.11/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark24PlanFactory.scala, spark-bigquery-pushdown/spark-2.4-bigquery-pushdown_2.12/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark24PlanFactory.scala, spark-bigquery-pushdown/spark-3.1-bigquery-pushdown_2.12/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark31PlanFactory.scala, spark-bigquery-pushdown/spark-3.2-bigquery-pushdown_2.13/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark32PlanFactory.scala, spark-bigquery-pushdown/spark-3.3-bigquery-pushdown_2.13/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark33PlanFactory.scala
The main implementation will be done in the next PR
=> Part 1: Added changes to support Spark 3.2/3.3 and other necessary changes for getting ordered results in df.show()

spark-bigquery-connector-common/third_party/apache-spark/src/main/java/com/google/cloud/spark/bigquery/ArrowSchemaConverter.java
Encountered these issues while running tpc-ds queries
=> Implemented methods for reading BigNumeric values and casting from Decimal to Bytes in Arrow

spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/BigQueryStrategy.scala, spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/SparkPlanFactory.scala, spark-bigquery-pushdown/pushdown_common_src/test/scala/com/google/cloud/spark/bigquery/pushdowns/BigQueryStrategySuite.scala, spark-bigquery-pushdown/spark-2.4-bigquery-pushdown_2.11/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark24ExpressionConverter.scala, spark-bigquery-pushdown/spark-2.4-bigquery-pushdown_2.12/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark24ExpressionConverter.scala, spark-bigquery-pushdown/spark-3.1-bigquery-pushdown_2.12/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark31ExpressionConverter.scala, spark-bigquery-pushdown/spark-3.2-bigquery-pushdown_2.13/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark32ExpressionConverter.scala, spark-bigquery-pushdown/spark-3.3-bigquery-pushdown_2.13/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark33ExpressionConverter.scala
=> Part 2: Implemented logic to ensure df.show() returns ordered results for top level order by

spark-bigquery-dsv1/spark-bigquery-dsv1-spark2-support/src/main/java/com/google/cloud/spark/bigquery/spark2/Spark2DataFrameToRDDConverter.java
TESTED=gpaste/5291600904192000
=> Fixed Scala 2.11 JavaConverters issue

cloudbuild/nightly.sh, cloudbuild/nightly.yaml
* Adding Spark 3.1 tests
* Copying Scala 2.13 to snapshots
* Increasing timeout
=> Updating the nightly task

bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClient.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/direct/BigQueryRDDFactory.java, spark-bigquery-dsv1/src/test/java/com/google/cloud/spark/bigquery/integration/DataSourceV1QueryPushdownIntegrationTest.java
Updated BigQueryClient to add query job labels while materializing query to table.
=> Added query job labels while materializing query to table

spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkFilterUtils.java, spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/SparkFilterUtilsTest.java
I noticed that this is not implemented but there doesn't seem to be clear reason why it's not as you can translate EqualNullSafe into a sql expression
=> Add support for EqualNullSafe pushdown

README-template.md, README.md
=> updating the read me for option clusteredFields, which was confusing

cloudbuild/nightly.sh, cloudbuild/nightly.yaml
=> Adding spark-3.3-bigquery to nightly run

spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/BigQueryDataSourceWriterInsertableRelation.java
We have another abort that needs to throw exception to ensure consistent behaviour
=> Issue #884 - Added exception for abort.

spark-bigquery-dsv2/spark-3.2-bigquery-lib/src/main/java/com/google/cloud/spark/bigquery/v2/Spark32BigQueryScanBuilder.java
Runtime filtering currently allows all columns of readSchema() as eligible for runtime filtering. 
It should only allow partition, clustering columns.
=> Fix runtime filtering by returning only partition,clustering fields

bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryDirectDataWriterHelper.java, bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/ReadRowsHelper.java, bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/StreamCombiningIterator.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/BigQueryDirectDataWriterContext.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/DataWriterContext.java
This PR reverts some of the code from PR #832
=> Fixing premature client closing in certain cases

spark-bigquery-dsv2/spark-3.1-bigquery-lib/src/main/java/com/google/cloud/spark/bigquery/v2/Spark31BigQueryScanBuilder.java, spark-bigquery-dsv2/spark-3.2-bigquery-lib/src/main/java/com/google/cloud/spark/bigquery/v2/Spark32BigQueryScanBuilder.java, spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/v2/context/BigQueryDataSourceReaderContext.java
Bloom filter currently does not get applied for the DSV2 connectors.
Results for TPCDS q40:
Before bloom filter plan: [image link](https://user-images.githubusercontent.com/25999807/221838984-5892f147-0bfb-4ee0-9e8e-0bc2d6c6bbb7.jpg)
After bloom filter plan: [image link](https://user-images.githubusercontent.com/25999807/221839003-ad10b568-4a9c-489a-b5d2-7e38ef8dd543.jpg)
=> Allow triggering bloom filter

CHANGES.md, README-template.md, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/AvroBinaryIterator.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/BigQueryRelation.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/ReadRowsResponseToInternalRowIteratorConverter.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SchemaConverters.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SchemaConvertersConfiguration.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConfig.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/direct/BigQueryRDDFactory.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/direct/Scala213BigQueryRDD.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/BigQueryDataSourceWriterInsertableRelation.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/BigQueryInsertableRelationBase.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/BigQueryWriteHelper.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/BigQueryDataSourceWriterModule.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/BigQueryDirectDataSourceWriterContext.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/BigQueryIndirectDataSourceWriterContext.java, spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/SchemaConverterTest.java, spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/SparkBigQueryConfigTest.java, spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/integration/IntegrationTestUtils.java, spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/integration/WriteIntegrationTestBase.java, spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/write/context/BigQueryDirectDataSourceWriterContextTest.java, spark-bigquery-dsv1/src/test/scala/com/google/cloud/spark/bigquery/SchemaConvertersSuite.scala, spark-bigquery-dsv1/src/test/scala/com/google/cloud/spark/bigquery/SchemaIteratorSuite.scala, spark-bigquery-dsv2/spark-3.1-bigquery-lib/src/main/java/com/google/cloud/spark/bigquery/v2/Spark3Util.java, spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/v2/context/BigQueryDataSourceReaderContext.java, spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/test/java/com/google/cloud/spark/bigquery/v2/context/BigQueryInputPartitionReaderContextTest.java, spark-bigquery-scala-212-support/src/main/java/com/google/cloud/spark/bigquery/direct/PreScala213BigQueryRDD.java
No functionality change in this PR. It was created to break the datetime/timestamp support to smaller easier to review PRs
=> Adding SchemaConvertersConfiguration preparing for the datetime update. 

spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryUtil.java
Co-authored-by: Emmanuel T Odeke <odeke-em@users.noreply.github.com>
=> Code simplification

CHANGES.md, bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryDirectDataWriterHelper.java
Code originally developed by vkarve, and adapted.
=> Enable async writes for greater throughput.

README-template.md, README.md
updating the readme to add how to create dataproc clusters with specfic connector jars
=> updating the readme

README-template.md, README.md, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SchemaConvertersConfiguration.java, spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConfig.java, spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/SchemaConverterTest.java, spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/SparkBigQueryConfigTest.java, spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/integration/IntegrationTestUtils.java, spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/integration/WriteIntegrationTestBase.java, spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/write/context/BigQueryDirectDataSourceWriterContextTest.java, spark-bigquery-dsv1/src/test/scala/com/google/cloud/spark/bigquery/SchemaConvertersSuite.scala, spark-bigquery-dsv1/src/test/scala/com/google/cloud/spark/bigquery/SchemaIteratorSuite.scala, spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/test/java/com/google/cloud/spark/bigquery/v2/context/BigQueryInputPartitionReaderContextTest.java
This config is not used anymore, and it's not planned to be used in the future.
=> Issue #1042: remove datetimeZoneId config

PUSHDOWN.md
Update spark-bigquery-support version from 0.27.0 to 0.27.1 inside the zip file extract
=> Update spark-bigquery-support version

spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/acceptance/AcceptanceTestConstants.java
Reverts GoogleCloudDataproc/spark-bigquery-connector#1329
=> Revert "Change the region of acceptance tests to us-west4"

spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/integration/SparkBigQueryIntegrationTestBase.java, spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/integration/TestDataset.java
Should solve flaky OpenLineageIntegrationTest runs
=> Creating unique dataset name per test name

spark-bigquery-parent/pom.xml
Based on the documentation in https://central.sonatype.org/publish/publish-portal-maven/
=> Using the new central-publishing-maven-plugin

CHANGES.md, bigquery-connector-common/pom.xml, bigquery-connector-common/src/test/java/com/google/cloud/bigquery/connector/common/ReadSessionCreatorTest.java, spark-bigquery-parent/pom.xml
One unit test was fixed due to change in the implementation of the BigQuery Storage library
=> Dependency updates
