build.sbt
project/plugins.sbt
src/main/scala/com/google/cloud/spark/bigquery/direct/DirectBigQueryRelation.scala

This change modifies the build process to automatically generate build-time configuration
constants such as project name and version, and uses them to generate a user-agent string
when constructing a new BigQuery storage client object.

Set the user-agent string for BQ storage.

---

build.sbt

and fix a typo in Google's company name

upgrade dependency bq storage client to v0.88.0-alpha

---

README.md

We need to use `%%` to make SBT add the `2.11` suffix to the artifact id, as explained on https://www.scala-sbt.org/1.x/docs/Library-Dependencies.html#Getting+the+right+Scala+version+with

Add a missing '%' in SBT dependency instructions

---

CHANGES.md
README.md
src/main/scala/com/google/cloud/spark/bigquery/SchemaConverters.scala
src/main/scala/com/google/cloud/spark/bigquery/SparkBigQueryOptions.scala
src/main/scala/com/google/cloud/spark/bigquery/direct/BigQueryRDD.scala
src/main/scala/com/google/cloud/spark/bigquery/direct/DirectBigQueryRelation.scala
src/test/scala/com/google/cloud/spark/bigquery/it/IntegrationTestUtils.scala
src/test/scala/com/google/cloud/spark/bigquery/it/SparkBigQueryEndToEndITSuite.scala

The BALANCED sharding strategy ensures balance among many streams on the
server-side, obviating the need for the client to mimic such behavior. Note that
I'm using an unknown field to force the BALANCED sharding strategy. We are in
the process of releasing new Java libraries. Once the new libraries are out, I
will send another pull request to use the generated code for setting the
sharding strategy.

Replace the manual skewing code with the BALANCED sharding strategy

---

examples/python/query_results.py

Caveat this approach currently only supports results of 10MB or more. Users would have to manually save smaller queries to a temp Dataset possibly with a TTL.
I think we could add this functionality to the connector without too much work. Maybe we should file a PR, but either way the documentation works.

Add example querying from BigQuery and loading the results into Spark

---

README.md

In my previous pull request, I accidentally forgot to remove one of the paragraphs.

Remove unneeded paragraph about partitioning

---

build.sbt

This is in preparation of changed coming in from https://github.com/GoogleCloudPlatform/spark-bigquery-connector/pull/29.

Bump the version

---

build.sbt
src/main/scala/com/google/cloud/spark/bigquery/direct/DirectBigQueryRelation.scala

As part of this change, we can now call setShardingStrategy() instead of relying on the unknown fields proto API for setting the sharding strategy.

Update the BigQuery Storage API client

---

src/main/scala/com/google/cloud/spark/bigquery/direct/DirectBigQueryRelation.scala
src/test/scala/com/google/cloud/spark/bigquery/DirectBigQueryRelationSuite.scala
src/test/scala/com/google/cloud/spark/bigquery/it/SparkBigQueryEndToEndITSuite.scala

This change modifies the filtering support in the direct BigQuery
relation to reflect the full set of filters which are supported by
the storage API. Notably, this includes:
- Support for multi-clause predicates (e.g. AND, OR, and NOT).
- Support for pseudo-column variables (_PARTITIONDATE) for ingestion
time partitioned tables.
- Support for additional filter operations (IsNull, IsNotNull, In,
StringStartsWith, StringEndsWith, StringContains).

Update filtering support.

---

src/main/scala/com/google/cloud/spark/bigquery/BigQueryInsertableRelation.scala
src/main/scala/com/google/cloud/spark/bigquery/BigQueryRelation.scala
src/main/scala/com/google/cloud/spark/bigquery/BigQueryRelationProvider.scala
src/main/scala/com/google/cloud/spark/bigquery/BigQueryWriteHelper.scala
src/main/scala/com/google/cloud/spark/bigquery/examples/Shakespeare.scala
src/main/scala/com/google/cloud/spark/bigquery/package.scala

- A NPE in the shutdown hook has occurred in case the delete had succeeded in the first time. The method now verifies the path exists before trying to delete it.
- Added support for data.write.bigquery("table") implicit import, fixed regression caused by relying of shaded scalalogging

Minor fixes

---

README.md

Readme typo BigQeury -> BigQuery

---

src/main/scala/com/google/cloud/spark/bigquery/direct/DirectBigQueryRelation.scala
src/test/scala/com/google/cloud/spark/bigquery/DirectBigQueryRelationSuite.scala
src/test/scala/com/google/cloud/spark/bigquery/it/SparkBigQueryEndToEndITSuite.scala

Following https://stackoverflow.com/questions/58766857/ it appears that having a warn level for this message is too severe, is it may occur according to the BigQuery Storage API, see the description of the requestedStreams parameter in [the API](https://googleapis.dev/java/google-cloud-clients/latest/com/google/cloud/bigquery/storage/v1beta1/BigQueryStorageClient.html#createReadSession-com.google.cloud.bigquery.storage.v1beta1.TableReferenceProto.TableReference-java.lang.String-int-).

Fixing log severity

---

src/main/scala/com/google/cloud/spark/bigquery/BigQueryWriteHelper.scala

Currently, when writing delta tables we have _committed _started _SUCCESS file. So we need to filter only using the temporary format

Fix filter when sending load job to Big Query

---

CHANGES.md
build.sbt
connector/src/main/scala/com/google/cloud/spark/bigquery/BigQueryRelationProvider.scala
connector/src/main/scala/com/google/cloud/spark/bigquery/BigQueryUtil.scala
connector/src/main/scala/com/google/cloud/spark/bigquery/direct/DirectBigQueryRelation.scala
connector/src/test/scala/com/google/cloud/spark/bigquery/it/SparkBigQueryEndToEndITSuite.scala
project/plugins.sbt
project/project/assembly.sbt

* Issue #72: Moved the shaded jar name from classifier to a new artifact name
* Issues #73, #87: Added better logging to help understand which columns and filters
are asked by spark, and which are passed down to BigQuery
* Issue #107: The connector will now alert when is is used with the wrong scala version

Bug Fixes and some cleanups

---

build.sbt
connector/src/main/scala/com/google/cloud/spark/bigquery/BigQueryUtil.scala
connector/src/main/scala/com/google/cloud/spark/bigquery/direct/BigQueryRDD.scala
connector/src/main/scala/com/google/cloud/spark/bigquery/direct/DirectBigQueryRelation.scala
connector/src/test/java/com/google/cloud/spark/bigquery/MockResponsesBatch.java
connector/src/test/scala/com/google/cloud/spark/bigquery/ReadRowsSuite.scala

This change switches the BigQuery Spark connector to use the BigQuery Storage API latest beta version, v1beta2.
The location of the v1beta2 client is:
https://github.com/googleapis/java-bigquerystorage/tree/master/google-cloud-bigquerystorage/src/main/java/com/google/cloud/bigquery/storage/v1beta2
Service protos:
https://github.com/googleapis/googleapis/tree/master/google/cloud/bigquery/storage/v1beta2
Verified locally by running integraion tests and the Python example 'shakespeare.py'.

Update the connector to use BigQuery Storage API v1beta2.

---

CHANGES.md
README.md
connector/src/main/scala/com/google/cloud/spark/bigquery/SparkBigQueryOptions.scala
connector/src/main/scala/com/google/cloud/spark/bigquery/direct/DirectBigQueryRelation.scala
connector/src/test/scala/com/google/cloud/spark/bigquery/DirectBigQueryRelationSuite.scala
connector/src/test/scala/com/google/cloud/spark/bigquery/SparkBigQueryOptionsSuite.scala

- Changed the `parallelism` parameter to `maxParallelism` in order to reflect the Change in the underlining API.
- Updated the README 
- Documented changes in the CHANGES.md file

PR #126 followup: parameter change

---

README.md
build.sbt
connector/src/main/java/com/google/cloud/spark/bigquery/examples/JavaShakespeare.java
connector/src/main/scala/com/google/cloud/spark/bigquery/examples/Shakespeare.scala
connector/src/test/scala/com/google/cloud/spark/bigquery/it/SparkBigQueryEndToEndITSuite.scala
examples/notebooks/Top words in Shakespeare by work.ipynb
examples/python/shakespeare.py

The old reference we've used (`pubblicdata`) is causing internal errors on the server side

Changing the refernce of the public data sets to bigquery-public-data

---

connector/src/main/scala/com/google/cloud/spark/bigquery/SparkBigQueryOptions.scala

With this change, the user can pass the access token to the spark with conf `spark.gcs.user.accessToken` and the same will be used for the authorization of the big-query resources.
This change still does not support refreshing the access token on expiry which would become an issue for the long-running spark applications.
I am currently thinking of this approach to solve this - 
1. User passes the refresh token, client ID and client secret to Spark along with the access token if she wants to auto-refresh the access token.
2. When the BigQueryRelation gets created, on the driver,  generate the access token if not already available. 
3. Broadcast the generated access token so that each executor has access to it.
4. Run a daemon thread on the driver which asynchronously refreshes the access …

Use access token for the Authorisation

---

connector/src/main/scala/com/google/cloud/spark/bigquery/SparkBigQueryOptions.scala
connector/src/test/scala/com/google/cloud/spark/bigquery/SparkBigQueryOptionsSuite.scala

Adding the option to add the spark.datasource.bigquery prefix to the configuration optionss in order to support the --conf command line flag

Supporting spark.datasource.bigquery prefix

---

connector/src/main/scala/com/google/cloud/spark/bigquery/direct/DirectBigQueryRelation.scala

Here's a fix for filter push down for views. I've moved temp table creation to the moment when "buildScan" is invoked. The defaultTableDefinition type is changed to "TableDefinition" and a separate method "getNumBytes" is created to calculate the size of the table. The "getNumBytes" returns zero bytes for views, and that should be fine as the important part is that the connector calculates the number of partitions after the temp table is generated and by that time the getNumBytes will be called on the temp table, not the view.

Do filter push down when reading from views

---

connector/src/main/scala/com/google/cloud/spark/bigquery/SparkBigQueryOptions.scala
connector/src/test/scala/com/google/cloud/spark/bigquery/it/SparkBigQueryEndToEndITSuite.scala

Simplifying the usage of the connector, instead of the `table` option, the usage can be the more common:
```
df = spark.read.format("bigquery").load(<table>)
df.write.format("bigquery").save(<table>)
```

Simplifying the usage

---

connector/src/main/java/com/google/cloud/bigquery/connector/common/ReadRowsHelper.java
connector/src/main/java/com/google/cloud/spark/bigquery/v2/ArrowColumnBatchPartitionReader.java
connector/src/main/java/com/google/cloud/spark/bigquery/v2/ArrowInputPartition.java
connector/src/main/java/com/google/cloud/spark/bigquery/v2/BigQueryDataSourceReader.java

This bypasses most of the existing translation code for the following reasons:
1.  I think there might be a memory leak because the existing code doesn't close the allocator.
2.  This avoids continuously recopying the schema.
I didn't delete the old code because it appears the BigQueryRDD still relies on it partially.
I also couldn't find instructions on formatting/testing (I couldn't find explicit unit tests
for existing arrow code, I'll update accordingly if pointers can be provided).

Adds implementation for supporting columnar batch reads from Spark.

---

connector/src/main/java/com/google/cloud/spark/bigquery/ProtobufUtils.java
connector/src/main/java/com/google/cloud/spark/bigquery/SchemaConverters.java
connector/src/test/java/com/google/cloud/spark/bigquery/ProtobufUtilsTest.java
connector/src/test/java/com/google/cloud/spark/bigquery/SchemaConverterTest.java

Changed the naming of a nested type in `testBigQueryToProtoSchema` in file ProtobufUtilsTest, in NESTED_STRUCT.
Error was previously uncaught as nested type names are apparently not compared in equality checks by the current google-cloud-bigquerystorage and google-cloud-bigquery, but they are in the newer versions.

Issue #221: Fixing ProtobufUtilsTest.java with newer BigQuery dependencies

---

connector/src/main/scala/com/google/cloud/spark/bigquery/BigQueryRelationProvider.scala
connector/src/main/scala/com/google/cloud/spark/bigquery/BigQueryUtil.scala
connector/src/main/scala/com/google/cloud/spark/bigquery/direct/DirectBigQueryRelation.scala

For some reason the BigQuery client was created by two scala methods, one was setting the parentProject and one was not. This has caused issue when the parent project was different from the cluster or the data projects.

Ensuring that BigQuery client will have the proper project id

---

connector/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConfig.java
connector/src/main/java/com/google/cloud/spark/bigquery/v2/SparkBigQueryConnectorModule.java
connector/src/main/scala/com/google/cloud/spark/bigquery/BigQueryRelationProvider.scala
connector/src/test/java/com/google/cloud/spark/bigquery/SparkBigQueryConfigTest.java
connector/src/test/scala/com/google/cloud/spark/bigquery/SparkBigQueryOptionsSuite.scala

PR #240 has unified the use of `SparkBigQueryConfig` also for the original DataSource v1 implementation, used in Spark 3. This implementation relies on `org.apache.spark.sql.sources.v2.DataSourceOptions` which does not exist in Spark 3 due to the massive DataSource API change it had.
This PR addresses that by:
* Removing `DataSourceOptions` from `SparkBigQueryConfig`
* Adding acceptance test for Dataproc image 2.0 (currently in preview), with Spark 3

Fixing Spark 3 compatibility

---

connector/src/main/java/com/google/cloud/spark/bigquery/SparkFilterUtils.java
connector/src/main/scala/com/google/cloud/spark/bigquery/direct/DirectBigQueryRelation.scala
connector/src/test/java/com/google/cloud/spark/bigquery/SparkFilterUtilsTest.java
connector/src/test/scala/com/google/cloud/spark/bigquery/DirectBigQueryRelationSuite.scala

This fixes the query failures similar to TPCDS query# 83. Without this fix, BigQuery read API complains that the pushed down filter is invalid. The fix is done for both the v1 and v2 code paths.
Testing: unit testing and tested with TPCDS query# 83

Convert filters on BigQuery dates and timestamp fields using the right type

---

connector/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConfig.java
connector/src/test/java/com/google/cloud/spark/bigquery/SparkBigQueryConfigTest.java

A regression bug preventing the usage of the `--conf` parameter to configure the connector's option has been introduced in version 0.17.2. This PR fixes that

Fixing external configuration regression bug

---

connector/src/main/scala/com/google/cloud/spark/bigquery/BigQueryRelation.scala

Tested by running a Spark job.

Change to BigQueryRelation so that the query plans are readable in Spark UI

---

connector/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConfig.java
connector/src/main/scala/com/google/cloud/spark/bigquery/BigQueryWriteHelper.scala
connector/src/test/java/com/google/cloud/spark/bigquery/SparkBigQueryConfigTest.java

In order to be able to load a BigQuery table partitioned on a DATE column using Avro, the option `useAvroLogicalTypes` has to be activated in `LoadJobConfiguration`. Otherwise, BigQuery reads DATE columns as INTEGER as documented here: https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-avro#logical_types

Add option to enable useAvroLogicalTypes option in LoadJobConfiguration

---

build.sbt

Without this override intellij is not able to fetch the proper version of slf4j-api and fails the compilation

PR #298 follow-up: Overriding slf4j-api version for Intellij

---

connector/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClient.java
connector/src/main/java/com/google/cloud/bigquery/connector/common/ReadSessionCreator.java
connector/src/main/java/com/google/cloud/spark/bigquery/DataSourceVersion.java
connector/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConfig.java
connector/src/main/java/com/google/cloud/spark/bigquery/v2/BigQueryDataSourceReaderModule.java
connector/src/main/java/com/google/cloud/spark/bigquery/v2/BigQueryDataSourceV2.java
connector/src/main/java/com/google/cloud/spark/bigquery/v2/SparkBigQueryConnectorModule.java
connector/src/main/scala/com/google/cloud/spark/bigquery/BigQueryInsertableRelation.scala
connector/src/main/scala/com/google/cloud/spark/bigquery/BigQueryRelationProvider.scala
connector/src/main/scala/com/google/cloud/spark/bigquery/BigQueryStreamWriter.scala
connector/src/main/scala/com/google/cloud/spark/bigquery/BigQueryStreamingSink.scala
connector/src/main/scala/com/google/cloud/spark/bigquery/BigQueryWriteHelper.scala
connector/src/test/scala/com/google/cloud/spark/bigquery/BigQueryRelationProviderSuite.scala
connector/src/test/scala/com/google/cloud/spark/bigquery/it/SparkBigQueryEndToEndReadFromQueryITSuite.scala

Adding the option to run an ad-hoc query on BigQuery and then read the result directly into a dataframe. The syntax is in the following manner:
```
df = df = spark.read.format("bigquery")
.option("viewsEnabled", true)
.option("materializationDataset", <dataset>)
.load("SELECT ...")
```
or
```
df = df = spark.read.format("bigquery")
.option("viewsEnabled", true)
.option("materializationDataset", <dataset>)
.option("query", "SELECT ...")
.load()
```
The queries are materialized to a temporary table and are re-used if the same query is used. For example
`df.select("col1").where("condition")` should use the temporary table and not re-run the query.
This also gives the option to efficiently run complex queries using joins on BigQuery specific functions from spark.

Adding read from query capability

---

build.sbt
connector/src/main/java/com/google/cloud/spark/bigquery/v2/BigQueryIndirectDataSourceWriter.java
connector/src/main/java/com/google/cloud/spark/bigquery/v2/BigQueryIndirectDataWriterFactory.java

Taking `SerializableConfiguration `from Apache-Beam rather than from a spark private API. This had worked with Scala 2.11 but fails with Scala 2.12.

Solving Scala 2.12 private API dependency

---

connector/src/main/java/com/google/cloud/spark/bigquery/v2/BigQueryDataSourceV2.java
connector/src/main/java/com/google/cloud/spark/bigquery/v2/SparkBigQueryConnectorModule.java
connector/src/main/scala/com/google/cloud/spark/bigquery/BigQueryRelationProvider.scala

Following the suggestions from #242 This implementation relies on org.apache.spark.sql.sources.v2.DataSourceOptions which does not exist in Spark 3 due to the massive DataSource API change it had.
This PR addresses that by:
Removing DataSourceOptions from SparkBigQueryConnectorModule.jav and BigQueryRelationProvider.scala

Spark 3 compatibility fixes

---

build.sbt

Some of the newer dependencies caused networking issues. The rollback has been tested and shown that it resolves these issues.

Reverting dependency updates

---

build.sbt

Tested:
```
$ unzip -l ~/.m2/repository/com/google/cloud/spark/spark-bigquery-with-dependencies_2.11/0.19.2-SNAPSHOT/spark-bigquery-with-dependencies_2.11-0.19.2-SNAPSHOT.jar | grep netty_tcnative
1933284  02-24-2021 15:34   META-INF/native/libcom_google_cloud_spark_bigquery_repackaged_netty_tcnative_linux_aarch64.so
2628280  02-24-2021 15:34   META-INF/native/libcom_google_cloud_spark_bigquery_repackaged_netty_tcnative_linux_x86_64.so
2714596  02-24-2021 15:34   META-INF/native/libcom_google_cloud_spark_bigquery_repackaged_netty_tcnative_osx_x86_64.jnilib
2425856  02-24-2021 15:34   META-INF/native/com_google_cloud_spark_bigquery_repackaged_netty_tcnative_windows_x86_64.dll
```

Issue #326: Fixing netty_tcnative_windows.dll shading

---

project/plugins.sbt

Without this upgrade shading was not working properly for me when
developing locally.  The shaded classes where getting repackaged but
the unshaded classes where not updates to to the repackaged classes.

Upgrade sbt-assembly

---

build.sbt
connector/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClient.java
connector/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryReadClientFactory.java
connector/src/main/java/com/google/cloud/bigquery/connector/common/ReadRowsHelper.java
connector/src/main/java/com/google/cloud/bigquery/connector/common/ReadSessionCreator.java
connector/src/main/java/com/google/cloud/bigquery/connector/common/ReadSessionCreatorConfig.java
connector/src/main/java/com/google/cloud/bigquery/connector/common/ReadSessionCreatorConfigBuilder.java
connector/src/main/java/com/google/cloud/spark/bigquery/ArrowBinaryIterator.java
connector/src/main/java/com/google/cloud/spark/bigquery/SchemaConverters.java
connector/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConfig.java
connector/src/main/java/com/google/cloud/spark/bigquery/v2/ArrowColumnBatchPartitionReader.java
connector/src/main/java/com/google/cloud/spark/bigquery/v2/ArrowInputPartition.java
connector/src/main/java/com/google/cloud/spark/bigquery/v2/BigQueryDataSourceReader.java
connector/src/main/java/com/google/cloud/spark/bigquery/v2/BigQueryInputPartition.java
connector/src/main/scala/com/google/cloud/spark/bigquery/direct/DirectBigQueryRelation.scala
connector/src/test/java/com/google/cloud/bigquery/connector/common/ReadRowsHelperTest.java
connector/src/test/java/com/google/cloud/bigquery/connector/common/ReadSessionCreatorTest.java
connector/src/test/java/com/google/cloud/spark/bigquery/SparkBigQueryConfigTest.java
connector/src/test/java/com/google/cloud/spark/bigquery/v2/BigQueryInputPartitionTest.java
connector/src/test/scala/com/google/cloud/spark/bigquery/DirectBigQueryRelationSuite.scala

Adds options for:
- Endpoint of the Read API - Useful for testing and if we migrate to regional endpoints
- Encoded base CreateReadSessionRequest which allows for setting hidden fields if necessary
- Arrow compression codec - This isn't hooked up yet in Arrow code (we need to wait until Arrow 4.0)
Additionally
- Fix some formatting from prior commits.
- Force version of guava to not be android (otherwise compilation/intellij are flaky)
- Introduce new configuration object for ReadRows calls

Add configuration options.

---

build.sbt
connector/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryStorageReadRowsTracer.java
connector/src/main/java/com/google/cloud/bigquery/connector/common/IteratorMultiplexer.java
connector/src/main/java/com/google/cloud/bigquery/connector/common/ParallelArrowReader.java
connector/src/main/java/com/google/cloud/bigquery/connector/common/ReadRowsHelper.java
connector/src/main/java/com/google/cloud/bigquery/connector/common/ReadRowsResponseInputStreamEnumeration.java
connector/src/main/java/com/google/cloud/bigquery/connector/common/ReadSessionCreatorConfig.java
connector/src/main/java/com/google/cloud/bigquery/connector/common/ReadSessionCreatorConfigBuilder.java
connector/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConfig.java
connector/src/main/java/com/google/cloud/spark/bigquery/v2/ArrowColumnBatchPartitionReader.java
connector/src/main/java/com/google/cloud/spark/bigquery/v2/ArrowInputPartition.java
connector/src/test/java/com/google/cloud/bigquery/connector/common/IteratorMultiplexerTest.java
connector/src/test/java/com/google/cloud/bigquery/connector/common/ParallelArrowReaderTest.java
connector/src/test/java/com/google/cloud/bigquery/connector/common/ReadSessionCreatorTest.java
connector/src/test/java/com/google/cloud/spark/bigquery/v2/BigQueryInputPartitionTest.java
connector/src/test/scala/com/google/cloud/spark/bigquery/it/SparkBigQueryEndToEndReadITSuite.scala

- This can potentially help mitigate any overhead decompression adds.  
- Fixed some bugs with existing classes along with some additional refactoring:
*  Move enumeration to its own class under common.
*  Don't rethrow for multiplexer or parrallel arrow reader on close (this breaks the ".show" use-case
* Make sure not to lose track of a future when background thread in parallel reader can be interrupted on placing into 
the queue.
*  Adds some more logging.
- Makes better use of child allocators to appropriately track memory for each thread (and remove a previously unncessary child allocator).
One more interesting extension that might help improve throghput is adding more then 1 stream per partition (might improve throughput).

Add option for background threaded reads for Arrow DSv2

---

connector/src/main/java/com/google/cloud/bigquery/connector/common/ParallelArrowReader.java

The additional of volatile for currentFuture is likely needed for
correctness.  Otherwise when closing the reader there are likely
no guarantees that a non-null value will be seen from the closing thread
and therefore a memory leak can occur.

Fix variable declarations in ParallelArrowReader.

---

connector/src/main/java/com/google/cloud/bigquery/connector/common/NonInterruptibleBlockingBytesChannel.java
connector/src/main/java/com/google/cloud/bigquery/connector/common/ParallelArrowReader.java
connector/src/main/java/com/google/cloud/spark/bigquery/v2/ArrowColumnBatchPartitionReader.java
connector/src/test/java/com/google/cloud/bigquery/connector/common/ParallelArrowReaderTest.java

for some reason I did not think Spark would interrupted the thread calling
the next() method, I had trouble tracking this down but thinking more thorougly
about it I think spark could and probably does do this.  In this case
if the thread was interrupted while trying to get the next batch it is
possible for a memory leak to occur.
This also rearranges the close order for DSv2, so that everything shutdown more cleanly, this also could avoid whatever edge case we are seeing with memory leaks.
Unfortunately, the unit test change didn't replicate the flakiness, but
I still think these changes make the code safer.

Fix next() to be interrupt safe.

---

README.md
connector/src/main/java/com/google/cloud/bigquery/connector/common/ReadSessionCreatorConfig.java
connector/src/main/java/com/google/cloud/bigquery/connector/common/ReadSessionCreatorConfigBuilder.java
connector/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConfig.java
connector/src/main/java/com/google/cloud/spark/bigquery/SparkFilterUtils.java
connector/src/main/java/com/google/cloud/spark/bigquery/v2/BigQueryDataSourceReader.java
connector/src/main/scala/com/google/cloud/spark/bigquery/direct/DirectBigQueryRelation.scala
connector/src/test/java/com/google/cloud/spark/bigquery/SparkFilterUtilsTest.java
connector/src/test/scala/com/google/cloud/spark/bigquery/DirectBigQueryRelationSuite.scala

This PR modifies the filter handling code so that connector pushes all the filters it is handed by spark to the BigQuery Storage API for the read case. There is still an option to disable this (set `pushAllFilters` to `False`) so if spark tries to pushes something Storage API can't handle, users can turn this feature off.

Push all filters to BigQuery Storage API

---

build.sbt
connector/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConnectorUserAgentProvider.java
connector/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConnectorVersionProvider.java
connector/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryUtil.java

When using Arrow compression in Spark 2.4 the user need to add `--conf spark.executor.userClassPathFirst=true --conf spark.driver.userClassPathFirst=true --packages com.github.luben:zstd-jni:1.4.9-1` to the spark-submit

Moved zstd-jni library to be provided in order to solve Spark 2.4 compatibility

---

connector/src/main/java/com/google/cloud/bigquery/connector/common/IteratorMultiplexer.java
connector/src/main/java/com/google/cloud/bigquery/connector/common/ParallelArrowReader.java
connector/src/main/java/com/google/cloud/spark/bigquery/v2/ArrowColumnBatchPartitionReader.java
connector/src/test/java/com/google/cloud/bigquery/connector/common/IteratorMultiplexerTest.java
connector/src/test/java/com/google/cloud/bigquery/connector/common/ParallelArrowReaderTest.java

- Simplify threaded model for multiplexer and parallel arrow reader.
This uses the same model that gRPC users where all messages for
consumers go through the same queue and a sentiel/exception is used
placed in the queue to notify of an error. This is a simplication and
is not involved in the bug fix. A semaphore is introduced to prevent
the queues from filling.
- For parallel arrow reader.  Create the batch as part of the task
submitted to the thread pool, this eliminates complicated future
handling code.
- In ArrowColumnBatchPartitionReader don't instantiate SequenceInputStream
unless it is needed.  SequenceInputStream preconsumes records so for
the multithreaded case pages are lost (actual bug fix).

Fix bug where background threads > 2 cases would miss pages

---

connector/third_party/apache-spark/src/main/java/com/google/cloud/spark/bigquery/ArrowSchemaConverter.java

We are already doing most of the calculation without it and using the
accessor redoes some (relatively) minor calculation.

Don't use NullableVectorHolder for strings.

---

connector/src/main/java/com/google/cloud/bigquery/connector/common/ReadRowsHelper.java
connector/src/main/java/com/google/cloud/bigquery/connector/common/ReadSessionCreatorConfig.java
connector/src/main/java/com/google/cloud/bigquery/connector/common/ReadSessionCreatorConfigBuilder.java
connector/src/main/java/com/google/cloud/bigquery/connector/common/StreamCombiningIterator.java
connector/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConfig.java
connector/src/main/java/com/google/cloud/spark/bigquery/v2/ArrowInputPartition.java
connector/src/main/java/com/google/cloud/spark/bigquery/v2/BigQueryDataSourceReader.java
connector/src/test/java/com/google/cloud/bigquery/connector/common/ReadRowsHelperTest.java
connector/src/test/java/com/google/cloud/spark/bigquery/v2/BigQueryInputPartitionTest.java

- Adds option to prebuffer more then 1 response at a time. This is
useful for high latency environments.
- Adds option to combine streams into one partition. This is useful if
there are more streams per core, and the time spent in spark
processing is significantly less then the time spent receiving data
from the server.  One case where this can occur is with partially
restricted push down filters.
This is done by adapting ResponseObserver from gax to support retries,
multiple streams and prebuffering.  Most of the complexity is because
of retries, which should soon be handled by the underlying client.
I'll be experimenting with parameters here to see if there are better
defaults.

Add options for tuning ReadRowsCalls.

---

spark-bigquery-parent/pom.xml

This version includes necessary changes to handle certain
RESOURCE_EXHAUSTED errors returned from Bigquery sStorage Read
service.

Update google-cloud-bom to 0.161.0 in order to update google-cloud-bigquerystorage dependency to 2.1.2

---

bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClient.java
spark-bigquery-dsv1/src/main/scala/com/google/cloud/spark/bigquery/BigQueryRelationProvider.scala
spark-bigquery-dsv1/src/main/scala/com/google/cloud/spark/bigquery/direct/DirectBigQueryRelation.scala

Testing: existing unit testing pass, end-to-end tests

Allow Reading of External Tables in Spark Connector

---

README.md

"byt" -> "by" (seems to be a typo)
Hello, it seems to be a typo (the details can be found in the following pic)

"byt" -> "by" (seems to be a typo)

---

README.md

Now that 0.23.0 has been released, add documentation regarding Arrow compression

Add documentation for arrow compression options

---

README.md
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClient.java
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClientFactoryConfig.java
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClientModule.java
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryConfig.java
bigquery-connector-common/src/test/java/com/google/cloud/bigquery/connector/common/BigQueryClientFactoryTest.java
spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConfig.java
spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/SparkBigQueryConfigTest.java
spark-bigquery-tests/src/main/java/com/google/cloud/spark/bigquery/integration/IntegrationTestUtils.java

Introduces new parameter `cacheExpirationTimeInMinutes` that defines the TTL of the in-memory cache for materialization to table. The TTL had been by default set to 15 minutes, it remained unchanged.
Tested in SparkBigQueryConfigTest.

Expose the cache expiration time as a parameter #518

---

spark-bigquery-dsv1/spark-bigquery-with-dependencies-parent/pom.xml
spark-bigquery-dsv2/spark-bigquery-dsv2-parent/pom.xml

According to https://github.com/luben/zstd-jni#limitations, the zstd-jni library should not be relocated. 
With this change, ZSTD Arrow compression can now be used without running into NoClassDefFoundError
Thank you @emkornfield!

Exclude com.github.luben.zstd from being shaded

---

.gitignore
bigquery-connector-common/pom.xml
coverage/pom.xml
pom.xml
spark-bigquery-connector-common/pom.xml
spark-bigquery-dsv1/pom.xml
spark-bigquery-dsv1/spark-bigquery-dsv1-parent/pom.xml
spark-bigquery-dsv1/spark-bigquery-dsv1-spark3-support/pom.xml
spark-bigquery-dsv1/spark-bigquery-with-dependencies-parent/pom.xml
spark-bigquery-dsv1/spark-bigquery-with-dependencies_2.11/pom.xml
spark-bigquery-dsv1/spark-bigquery-with-dependencies_2.12/pom.xml
spark-bigquery-dsv1/spark-bigquery_2.11/pom.xml
spark-bigquery-dsv1/spark-bigquery_2.12/pom.xml
spark-bigquery-dsv2/pom.xml
spark-bigquery-dsv2/spark-2.4-bigquery/pom.xml
spark-bigquery-dsv2/spark-3.1-bigquery/pom.xml
spark-bigquery-dsv2/spark-bigquery-dsv2-common/pom.xml
spark-bigquery-dsv2/spark-bigquery-dsv2-parent/pom.xml
spark-bigquery-parent/pom.xml
spark-bigquery-pushdown/pom.xml
spark-bigquery-pushdown/spark-2.4-bigquery-pushdown_2.11/pom.xml
spark-bigquery-pushdown/spark-2.4-bigquery-pushdown_2.12/pom.xml
spark-bigquery-pushdown/spark-3.1-bigquery-pushdown_2.12/pom.xml
spark-bigquery-pushdown/spark-bigquery-dsv1-relation_2.11/pom.xml
spark-bigquery-pushdown/spark-bigquery-dsv1-relation_2.12/pom.xml
spark-bigquery-pushdown/spark-bigquery-pushdown-common_2.11/pom.xml
spark-bigquery-pushdown/spark-bigquery-pushdown-common_2.12/pom.xml
spark-bigquery-pushdown/spark-bigquery-pushdown-parent/pom.xml
spark-bigquery-python-lib/pom.xml
spark-bigquery-tests/pom.xml

Should simplify the release process, see https://maven.apache.org/maven-ci-friendly.html

Switched versions to use the ${revision} property

---

README.md
spark-bigquery-parent/pom.xml

As can be seen [here](https://github.com/netty/netty/blob/netty-4.1.73.Final/bom/pom.xml#L68) and [here](https://github.com/netty/netty/blob/netty-4.1.73.Final/bom/pom.xml#L306), we can get the correctly matched netty and netty-tcnative versions from the netty-bom itself

Remove the explicit dependency on netty-tcnative-boringssl-static

---

bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClient.java

I added a check to see if the `finishedJob` is `null`. If it is, then just re-throw the exception thrown by the `google-cloud-bigquery` library.

Handle the exception in load when job is not created

---

CONTRIBUTING.md
README.md
spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConfig.java
spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/SparkBigQueryConfigTest.java

Fix to the issue: https://github.com/GoogleCloudDataproc/spark-bigquery-connector/issues/593
changes to support cacheExpirationTimeInMinutes=0, if user wants to disable cache
Added unit test
Ran integration tests

changes to support cacheExpirationTimeInMinutes=0, if user wants to disable cache

---

spark-bigquery-dsv2/spark-2.4-bigquery/src/test/java/com/google/cloud/spark/bigquery/integration/Spark24DirectWriteIntegrationTest.java
spark-bigquery-dsv2/spark-2.4-bigquery/src/test/java/com/google/cloud/spark/bigquery/integration/Spark24IndirectWriteIntegrationTest.java

This was done by splitting the write test to two classes

Removed 2:45 minutes from the spark 2.4 integration test time 

---

spark-bigquery-parent/pom.xml

Remove the need for tty during singing so that gpg plugin can run from a headless script.
Add flag to allow splitting when the staging repo gets built and when it gets uploaded.

Add flags to support automated builds.

---

cloudbuild/nightly.sh
cloudbuild/nightly.yaml

Here, the script fails because we have not defined the `STEP` variable earlier

Fix the failing command in nightly.sh

---

README-template.md
README.md
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClient.java
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryUtil.java
bigquery-connector-common/src/test/java/com/google/cloud/bigquery/connector/common/BigQueryUtilTest.java
spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConfig.java
spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/SparkBigQueryConfigTest.java
spark-bigquery-dsv1/src/main/scala/com/google/cloud/spark/bigquery/BigQueryWriteHelper.scala
spark-bigquery-dsv2/spark-3.1-bigquery/src/test/java/com/google/cloud/spark/bigquery/integration/Spark31ReadIntegrationTest.java
spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/v2/context/BigQueryDirectDataSourceWriterContext.java
spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/v2/context/BigQueryIndirectDataSourceWriterContext.java
spark-bigquery-tests/src/main/java/com/google/cloud/spark/bigquery/integration/SparkBigQueryIntegrationTestBase.java
spark-bigquery-tests/src/main/java/com/google/cloud/spark/bigquery/integration/TestConstants.java
spark-bigquery-tests/src/main/java/com/google/cloud/spark/bigquery/integration/WriteIntegrationTestBase.java

Added field level schema check in indirect mode while writing data to BigQuery and an option (enableModeCheckForSchemaFields) to ignoring the mode, during field comparison

Added field level schema check in indirect mode and an option to ignoring the mode, during field comparison

---

spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/AggregateQuery.scala
spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/BigQuerySQLQuery.scala
spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/FilterQuery.scala
spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/ProjectQuery.scala
spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/SortLimitQuery.scala
spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/SourceQuery.scala
spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/SparkBigQueryPushdownUtil.scala
spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/SparkExpressionFactory.scala
spark-bigquery-pushdown/pushdown_common_src/test/scala/com/google/cloud/spark/bigquery/pushdowns/AggregateQuerySuite.scala
spark-bigquery-pushdown/pushdown_common_src/test/scala/com/google/cloud/spark/bigquery/pushdowns/FilterQuerySuite.scala
spark-bigquery-pushdown/pushdown_common_src/test/scala/com/google/cloud/spark/bigquery/pushdowns/ProjectQuerySuite.scala
spark-bigquery-pushdown/pushdown_common_src/test/scala/com/google/cloud/spark/bigquery/pushdowns/SortLimitQuerySuite.scala
spark-bigquery-pushdown/pushdown_common_src/test/scala/com/google/cloud/spark/bigquery/pushdowns/SourceQuerySuite.scala
spark-bigquery-pushdown/pushdown_common_src/test/scala/com/google/cloud/spark/bigquery/pushdowns/SparkBigQueryPushdownUtilSuite.scala
spark-bigquery-pushdown/pushdown_common_src/test/scala/com/google/cloud/spark/bigquery/pushdowns/TestConstants.scala
spark-bigquery-pushdown/spark-2.4-bigquery-pushdown_2.11/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark24ExpressionFactory.scala
spark-bigquery-pushdown/spark-2.4-bigquery-pushdown_2.12/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark24ExpressionFactory.scala
spark-bigquery-pushdown/spark-3.1-bigquery-pushdown_2.12/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark31ExpressionFactory.scala

Ran into an issue where one of the Spark expressions called `Alias` is not binary compatible between Spark versions. See https://stackoverflow.com/questions/66106096/delta-lake-insert-into-sql-in-pyspark-is-failing-with-java-lang-nosuchmethoder
So, created a Spark expression factory that can create Alias for specific Spark versions
Note that even though there are 18 changed files, most of the changes are pretty small. Basically, changing the method parameters

Created a Spark expression factory to avoid binary compatibility issues

---

spark-bigquery-dsv1/src/main/scala/com/google/cloud/spark/bigquery/BigQueryConnectorUtils.scala
spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/BigQueryStrategy.scala
spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/SparkBigQueryPushdown.scala
spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/SparkPlanFactory.scala
spark-bigquery-pushdown/spark-2.4-bigquery-pushdown_2.11/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark24BigQueryPushdown.scala
spark-bigquery-pushdown/spark-2.4-bigquery-pushdown_2.11/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark24BigQueryStrategy.scala
spark-bigquery-pushdown/spark-2.4-bigquery-pushdown_2.12/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark24BigQueryPushdown.scala
spark-bigquery-pushdown/spark-2.4-bigquery-pushdown_2.12/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark24BigQueryStrategy.scala
spark-bigquery-pushdown/spark-3.1-bigquery-pushdown_2.12/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark31BigQueryPushdown.scala
spark-bigquery-pushdown/spark-3.1-bigquery-pushdown_2.12/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark31BigQueryStrategy.scala

This PR is built on top of #621 and injects the SparkPlanFactory class into BigQueryStrategy.
This is done to extract out the logic of creating the SparkPlan in a separate class and to facilitate easier unit testing

Integrated SparkPlanFactory with BigQueryStrategy

---

spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/direct/BigQueryRDDFactory.java
spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/direct/DirectBigQueryRelation.java
spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/BigQuerySQLQuery.scala
spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/BigQueryStrategy.scala
spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/SourceQuery.scala
spark-bigquery-pushdown/pushdown_common_src/test/scala/com/google/cloud/spark/bigquery/pushdowns/AggregateQuerySuite.scala
spark-bigquery-pushdown/pushdown_common_src/test/scala/com/google/cloud/spark/bigquery/pushdowns/BigQueryStrategySuite.scala
spark-bigquery-pushdown/pushdown_common_src/test/scala/com/google/cloud/spark/bigquery/pushdowns/FilterQuerySuite.scala
spark-bigquery-pushdown/pushdown_common_src/test/scala/com/google/cloud/spark/bigquery/pushdowns/ProjectQuerySuite.scala
spark-bigquery-pushdown/pushdown_common_src/test/scala/com/google/cloud/spark/bigquery/pushdowns/SortLimitQuerySuite.scala
spark-bigquery-pushdown/pushdown_common_src/test/scala/com/google/cloud/spark/bigquery/pushdowns/SourceQuerySuite.scala
spark-bigquery-pushdown/pushdown_common_src/test/scala/com/google/cloud/spark/bigquery/pushdowns/TestConstants.scala

1) Added a find method to `BigQuerySQLQuery` class so that we can search for the `SourceQuery` in the tree and get `BigQueryRDDFactory` from it. `BigQueryRDDFactory` will then be used to create the RDD
2) Implemented BigQueryStrategy by integrating with various other helper classes. Also, added unit tests for the same.
Sanity tested the implementation by running an aggregation integration test

Completed implementation of BigQueryStrategy

---

README-template.md
spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/v2/context/BigQueryDataSourceWriterModule.java
spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/v2/context/BigQueryDirectDataSourceWriterContext.java
spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/test/java/com/google/cloud/spark/bigquery/v2/context/BigQueryDirectDataSourceWriterContextTest.java
spark-bigquery-tests/src/main/java/com/google/cloud/spark/bigquery/integration/WriteIntegrationTestBase.java

In PR#613, we have added the field level schema check for indirect write, matching it with that of direct write.
Also we have added an option **enableModeCheckForSchemaFields** which can be used to surpass the mode check for schema fields which was only supported in indirect write.
This PR is to support the same option in direct write as well

adding the option to disable mode check for direct write 

---

spark-bigquery-dsv1/spark-bigquery-with-dependencies-parent/pom.xml
spark-bigquery-dsv2/spark-bigquery-dsv2-parent/pom.xml
spark-bigquery-parent/pom.xml

removing conscrypt from shaded dependencies, so that it will be part of org/conscrypt since acceptance tests were failing in serverless with reason `failed to find class org/conscrypt/CryptoUpcalls`. Anyway we are not using the package `com.google.cloud.spark.bigquery.repackaged.org.conscrypt` anywhere in the code so it is safe to remove the shaded dependency

removing conscrypt from shaded dependencies 

---

bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryConfigurationUtil.java
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/IteratorMultiplexer.java
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/MaterializationConfiguration.java
bigquery-connector-common/src/test/java/com/google/cloud/bigquery/connector/common/BigQueryConfigurationUtilTest.java
spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConfig.java
spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConnectorModule.java
spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/SparkBigQueryConfigTest.java
spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/SparkBigQueryProxyAndHttpConfigTest.java
spark-bigquery-dsv1/src/main/scala/com/google/cloud/spark/bigquery/BigQueryRelationProvider.scala
spark-bigquery-dsv1/src/test/scala/com/google/cloud/spark/bigquery/SparkBigQueryOptionsSuite.scala
spark-bigquery-dsv2/spark-2.4-bigquery/src/main/java/com/google/cloud/spark/bigquery/v2/BigQueryDataSourceV2.java
spark-bigquery-dsv2/spark-3.1-bigquery/src/main/java/com/google/cloud/spark/bigquery/v2/BigQueryCatalog.java
spark-bigquery-dsv2/spark-3.1-bigquery/src/main/java/com/google/cloud/spark/bigquery/v2/BigQueryIdentifier.java
spark-bigquery-dsv2/spark-3.1-bigquery/src/main/java/com/google/cloud/spark/bigquery/v2/BigQueryTable.java
spark-bigquery-dsv2/spark-3.1-bigquery/src/main/java/com/google/cloud/spark/bigquery/v2/BigQueryTableProvider.java
spark-bigquery-dsv2/spark-3.1-bigquery/src/main/java/com/google/cloud/spark/bigquery/v2/BigQueryWriteBuilder.java
spark-bigquery-dsv2/spark-3.1-bigquery/src/test/java/com/google/cloud/spark/bigquery/integration/Spark31DirectWriteIntegrationTest.java
spark-bigquery-dsv2/spark-3.1-bigquery/src/test/java/com/google/cloud/spark/bigquery/integration/Spark31ReadByFormatIntegrationTest.java
spark-bigquery-dsv2/spark-3.1-bigquery/src/test/java/com/google/cloud/spark/bigquery/integration/Spark31ReadIntegrationTest.java
spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/v2/InjectorFactory.java
spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/v2/context/BigQueryDataSourceReaderModule.java
spark-bigquery-tests/src/main/java/com/google/cloud/spark/bigquery/integration/ReadByFormatIntegrationTestBase.java
spark-bigquery-tests/src/main/java/com/google/cloud/spark/bigquery/integration/ReadIntegrationTestBase.java

Spark Catalog API implementation is required for supporting write capabilities in spark 3. The main difference is that in previous version is a configuration scan on each load or save, while with the catalog there's a catalog creation based on the configuration (without getting a specific table) and them referring to the table when creating the ScanBuilder. 
This required breaking some of the configuration parsing logic, originally concentrated in SparkBigQueryConfig into new classes.

Spark Catalog first implementaiton

---

README-template.md
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClient.java
spark-bigquery-dsv1/src/main/scala/com/google/cloud/spark/bigquery/BigQueryWriteHelper.scala
spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/v2/context/BigQueryIndirectDataSourceWriterContext.java
spark-bigquery-tests/src/main/java/com/google/cloud/spark/bigquery/integration/SparkBigQueryIntegrationTestBase.java
spark-bigquery-tests/src/main/java/com/google/cloud/spark/bigquery/integration/TestConstants.java
spark-bigquery-tests/src/main/java/com/google/cloud/spark/bigquery/integration/WriteIntegrationTestBase.java

removing the schema level check for InDirect write and enabling the option enableModeCheckForSchemaFields only for Direct write

removing the schema level check for InDirect write 

---

spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SupportsQueryPushdown.java
spark-bigquery-dsv2/spark-2.4-bigquery/src/main/java/com/google/cloud/spark/bigquery/v2/BigQueryDataSourceReader.java
spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/v2/context/BigQueryDataSourceReaderContext.java
spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/v2/context/BigQueryDataSourceReaderModule.java

We will use the interface SupportsQueryPushdown for integrating with DSv2 connector for Spark 2.4 in the next PR. 
We need the `BigQueryRDDFactory` object for [SourceQuery](https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/master/spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/SourceQuery.scala#L33) in pushdown

Add interface SupportsQueryPushdown that is implemented by BigQueryDataSourceReader

---

cloudbuild/nightly.yaml

The nightly build is failing with an NPE because `BIGLAKE_CONNECTION_ID` is not set.
This PR fixes that

Add BIGLAKE_CONNECTION_ID as an env variable in the nightly script

---

spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/SparkExpressionConverter.scala
spark-bigquery-pushdown/pushdown_common_src/test/scala/com/google/cloud/spark/bigquery/pushdowns/SparkExpressionConverterSuite.scala

Changing the cast type to Numeric instead of Bytes if the expression is of Integer, Long, Float, Double and Decimal type

Changing the cast type to Numeric instead of Bytes

---

CHANGES.md
spark-bigquery-dsv2/spark-3.1-bigquery/src/main/java/com/google/cloud/spark/bigquery/v2/BigQueryTable.java
spark-bigquery-dsv2/spark-3.1-bigquery/src/test/java/com/google/cloud/spark/bigquery/integration/Spark31ReadFromQueryIntegrationTest.java

changing the read table during load from BigQueryClient.getTable to BigQueryClient.getReadTable to materialize Query to Table

Supporting load from query in spark-3.1-bigquery

---

spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/SparkExpressionConverter.scala
spark-bigquery-pushdown/pushdown_common_src/test/scala/com/google/cloud/spark/bigquery/pushdowns/SparkExpressionConverterSuite.scala

Previously, if the Literal pattern in Contains, EndsWith and StartsWith had a single quote, the pushdown would fail
With this change, the query is generated correctly 
Shakespeare.py example: df = df.where("word_count > 0 AND word NOT LIKE '%\\'%'") gets correctly generated as 
```
SELECT * FROM ( SELECT ( SUBQUERY_2.SUBQUERY_2_COL_0 ) AS SUBQUERY_3_COL_0 , ( SUM ( SUBQUERY_2.SUBQUERY_2_COL_1 ) ) AS SUBQUERY_3_COL_1 FROM ( SELECT ( SUBQUERY_1.WORD ) AS SUBQUERY_2_COL_0 , ( SUBQUERY_1.WORD_COUNT ) AS SUBQUERY_2_COL_1 FROM ( SELECT * FROM ( SELECT * FROM `bigquery-public-data.samples.shakespeare` AS BQ_CONNECTOR_QUERY_ALIAS ) AS SUBQUERY_0 WHERE ( ( SUBQUERY_0.WORD_COUNT > 0 ) AND NOT ( CONTAINS_SUBSTR ( SUBQUERY_0.WORD , '\'' ) ) ) ) AS SUBQUERY_1 ) AS SUBQUERY_2 GROUP BY …
```

Escape single quote in Contains, EndsWith and StartsWith

---

spark-bigquery-tests/src/main/java/com/google/cloud/spark/bigquery/integration/ReadByFormatIntegrationTestBase.java

Not sure why but the number of partitions for this table has doubled which was causing integration test failures

Increase number of partitions to 138 for natality table

---

pom.xml

The error is 
```
[ERROR] Project 'com.google.cloud.spark:spark-bigquery-pushdown-parent:0.27.0' is duplicated in the reactor -> [Help 1]
org.apache.maven.project.DuplicateProjectException: Project 'com.google.cloud.spark:spark-bigquery-pushdown-parent:0.27.0' is duplicated in the reactor
```

Avoiding DuplicateProjectException when using the dsv1 profile

---

spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/BigQueryStrategy.scala
spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/BinaryOperationExtractor.scala
spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/SparkExpressionConverter.scala
spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/UnaryOperationExtractor.scala
spark-bigquery-pushdown/pushdown_common_src/test/scala/com/google/cloud/spark/bigquery/pushdowns/UnaryOperationExtractorSuite.scala
spark-bigquery-pushdown/spark-2.4-bigquery-pushdown_2.11/src/test/scala/com/google/cloud/spark/bigquery/pushdowns/BinaryOperationExtractorSuite.scala
spark-bigquery-pushdown/spark-3.1-bigquery-pushdown_2.12/src/test/scala/com/google/cloud/spark/bigquery/pushdowns/BinaryOperationExtractorSuite.scala
spark-bigquery-pushdown/spark-3.3-bigquery-pushdown_2.13/src/main/scala/com/google/cloud/spark/bigquery/pushdowns/Spark33BigQueryPushdown.scala

From Spark 3.2 onwards, UnaryNode and BinaryNode have been changed to interfaces. In earlier Spark version they were classes.
So, this PR changes UnaryOperationExtractor and BinaryOperationExtractor to take LogicalPlan as input instead of UnaryNode/BinaryNode which preserves the compatibility between all the different Spark versions

Change UnaryOperationExtractor and BinaryOperationExtractor to take LogicalPlan instead of UnaryNode/BinaryNode

---

CHANGES.md
spark-bigquery-parent/pom.xml

More details at https://github.com/protocolbuffers/protobuf/security/advisories/GHSA-h4h5-3hr4-j3g2

Addressing CVE-2022-3171

---

spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/BigQuerySQLQuery.scala
spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/BigQueryStrategy.scala
spark-bigquery-pushdown/pushdown_common_src/main/scala/com/google/cloud/spark/bigquery/pushdowns/SparkBigQueryPushdownUtil.scala
spark-bigquery-pushdown/pushdown_common_src/test/scala/com/google/cloud/spark/bigquery/pushdowns/SparkBigQueryPushdownUtilSuite.scala

Changes to add a ProjectNode on top of existing ProjectNode when show() is called and if there is no limit applied on the query during pushdown.

Changes to add a ProjectNode on top of existing ProjectNode

---

cloudbuild/Dockerfile

Taken from https://cloud.google.com/sdk/docs/install (the "Docker Tip")

Adding gcloud CLI to nightly image

---

.github/workflows/codeql-analysis.yml

As required by https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/

Upgrading CodeQL GitHub action

---

bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryUtil.java
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/ReadRowsHelper.java
bigquery-connector-common/src/test/java/com/google/cloud/bigquery/connector/common/BigQueryUtilTest.java
spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryUtil.java
spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/SparkBigQueryUtilTest.java
spark-bigquery-dsv2/spark-3.1-bigquery-lib/src/main/java/com/google/cloud/spark/bigquery/v2/Spark31BigQueryScanBuilder.java
spark-bigquery-dsv2/spark-3.2-bigquery-lib/pom.xml
spark-bigquery-dsv2/spark-3.2-bigquery-lib/src/main/java/com/google/cloud/spark/bigquery/v2/Spark32BigQueryScanBuilder.java
spark-bigquery-dsv2/spark-3.2-bigquery/src/test/java/com/google/cloud/spark/bigquery/integration/Spark32ReadByFormatIntegrationTest.java
spark-bigquery-dsv2/spark-3.3-bigquery/src/test/java/com/google/cloud/spark/bigquery/integration/Spark33ReadByFormatIntegrationTest.java
spark-bigquery-dsv2/spark-3.3-bigquery/src/test/java/com/google/cloud/spark/bigquery/integration/Spark33ReadIntegrationTest.java
spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/v2/context/ArrowInputPartitionContext.java
spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/v2/context/BigQueryDataSourceReaderContext.java

Based on PR #687 
Co-Authored-By: Zhou Fang <coufon@users.noreply.github.com>

Support Spark dynamic partition pruning

---

README.md

I tested the spark-bigquery-with-dependencies 0.28 works for spark 3.3.1. but its probably missing the check mark on the readme, so just wanted to correct it, as I was almost thought i will have to move to scala 2_13 :) which is not required as it works fine.

spark-bigquery-with-dependencies missing checkmark for spark 3.3.1

---

spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/acceptance/AcceptanceTestConstants.java
spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/acceptance/AcceptanceTestUtils.java
spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/acceptance/BigNumericDataprocServerlessAcceptanceTestBase.java
spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/acceptance/DataprocServerlessAcceptanceTestBase.java
spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/acceptance/ReadSheakspeareDataprocServerlessAcceptanceTestBase.java
spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/acceptance/WriteStreamDataprocServerlessAcceptanceTestBase.java
spark-bigquery-dsv1/spark-bigquery-with-dependencies_2.12/src/test/java/com/google/cloud/spark/bigquery/acceptance/Scala212DataprocImage21AcceptanceTest.java
spark-bigquery-dsv1/spark-bigquery-with-dependencies_2.12/src/test/java/com/google/cloud/spark/bigquery/acceptance/Scala212DataprocImage21DisableConscryptAcceptanceTest.java

The PR has fix for the following build failures
```
Step #1 - "maven-build": [ERROR] com.google.cloud.spark.bigquery.acceptance.Scala212DataprocImage20DisableConscryptAcceptanceTest  Time elapsed: 104.765 s  <<< ERROR!
Step #1 - "maven-build": java.lang.IllegalStateException: Batch is empty
Step #1 - "maven-build": 	at com.google.common.base.Preconditions.checkState(Preconditions.java:502)
Step #1 - "maven-build": 	at com.google.api.client.util.Preconditions.checkState(Preconditions.java:92)
Step #1 - "maven-build": 	at com.google.api.client.googleapis.batch.BatchRequest.execute(BatchRequest.java:231)
Step #1 - "maven-build": 	at com.google.cloud.storage.spi.v1.HttpStorageRpc$DefaultRpcBatch.submit(HttpStorageRpc.java:263)
Step #1 - "maven-build": 	at …
```

fixing nightly build failures

---

CHANGES.md
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/ReadSessionCreator.java
bigquery-connector-common/src/test/java/com/google/cloud/bigquery/connector/common/ReadSessionCreatorTest.java

https://github.com/GoogleCloudDataproc/spark-bigquery-connector/issues/908

Issue #908: setting the preferred min parallelism to be not more than max parallelism

---

README-template.md
README.md
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClientFactoryConfig.java
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClientModule.java
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryConfig.java
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryCredentialsSupplier.java
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryUtil.java
bigquery-connector-common/src/test/java/com/google/cloud/bigquery/connector/common/BigQueryClientFactoryTest.java
bigquery-connector-common/src/test/java/com/google/cloud/bigquery/connector/common/BigQueryCredentialsSupplierTest.java
bigquery-connector-common/src/test/java/com/google/cloud/bigquery/connector/common/BigQueryUtilTest.java
bigquery-connector-common/src/test/java/com/google/cloud/bigquery/connector/common/integration/CustomCredentialsIntegrationTest.java
bigquery-connector-common/src/test/java/com/google/cloud/bigquery/connector/common/integration/DefaultCredentialsDelegateAccessTokenProvider.java
spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConfig.java

A replacement for https://github.com/GoogleCloudDataproc/spark-bigquery-connector/pull/811. The goal here is to let a custom `AccessTokenProvider` be passed optional configuration via read options.

Add support for passing configuration to custom AccessTokenProvider

---

spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/ArrowBinaryIterator.java
spark-bigquery-connector-common/third_party/apache-spark/src/main/java/com/google/cloud/spark/bigquery/ArrowSchemaConverter.java
spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/v2/context/ArrowColumnBatchPartitionReaderContext.java

- Make ArrowSchemaConverter Generic
- Changes all accessors to now extend ArrowSchemaConverter
- Instantiates new classes via static factory method instead of direct constructor.
- Moves null checks to each concrete implementation.  While I believe JVM should be able to optimize based on the parent method, I'm not 100% sure and this way JVM should be able to avoid megamorphic dispatch for sure (also eliminate old work around from a [bug in Arrow 0.9](https://github.com/apache/spark/commit/e50a37a587fd7db48b59e37f234f8c74bd6707f7) for checks.
- Move child fields to StructAccessor (hopefully keeps more common classes smaller).

Remove one level of indirection in ArrowSchemaConverter.

---

spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConfig.java

This would allow users to specify the maxParallelism as `spark.datasource.bigquery.maxParallelism`

Allow maxParallelism to be specified via spark properties

---

bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClientFactory.java
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClientFactoryConfig.java
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryConfig.java
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/StreamCombiningIterator.java
bigquery-connector-common/src/test/java/com/google/cloud/bigquery/connector/common/BigQueryClientFactoryTest.java
spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConfig.java
spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/SparkBigQueryConfigTest.java

- Add configuration to control netty flow control window size
- Add backpressure to StreamCombining iterator
Together these appear to improve over baseline performance when using parameters below by 10-15% over basic line items aggregation (on my cluster 330 seconds to 300 seconds or slightly less).  When trying to understand the impact of each change, it appears flow control + buffering responses accounts for 7-10%, the backpression accounts for 3-5% but seems to reduce overall variance across runs.
Also the backpressure potentially indicates we can additionally tune Netty/gRPC thread pools to potentially avoid contention. I think in general they use number of cores on the box for sizing which makes less sense if Spark splits executors across multiple JVMs on the same box (I don't have …

additional scan perf tuning.

---

bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/ReadSessionCreator.java
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/ReadSessionCreatorConfig.java
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/ReadSessionCreatorConfigBuilder.java
bigquery-connector-common/src/test/java/com/google/cloud/bigquery/connector/common/ReadSessionCreatorTest.java
spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConfig.java
spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/v2/context/BigQueryDataSourceReaderContext.java

ReadSession creation is a huge bottleneck for performance. Caching the ReadSession response allows queries to reuse the existing ReadSession when we encounter the same table, filters, columns combination.

Cache ReadSession response

---

CHANGES.md
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClientFactory.java
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryConfig.java
bigquery-connector-common/src/test/java/com/google/cloud/bigquery/connector/common/BigQueryClientFactoryTest.java

BigQueryConfig doesn't overwrite hashCode() and equals(), causing to create a client for every request.

changing the hash from BigQueryConfig to BigQueryClientFactoryConfig

---

CHANGES.md
README-template.md
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClientFactoryConfig.java
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClientModule.java
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryConfig.java
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryConfigurationUtil.java
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryCredentialsSupplier.java
bigquery-connector-common/src/test/java/com/google/cloud/bigquery/connector/common/BigQueryClientFactoryTest.java
bigquery-connector-common/src/test/java/com/google/cloud/bigquery/connector/common/BigQueryCredentialsSupplierTest.java
bigquery-connector-common/src/test/java/com/google/cloud/bigquery/connector/common/integration/CustomCredentialsIntegrationTest.java
spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConfig.java
spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/SparkBigQueryConfigTest.java

This is modeled after the GCS connector's implementation (https://github.com/GoogleCloudDataproc/hadoop-connectors/blob/master/gcs/CONFIGURATION.md#service-account-impersonation).

Add support for service account impersonation

---

spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/v2/context/BigQueryDataSourceReaderContext.java
spark-bigquery-parent/pom.xml

This will enable broadcast joins (without AQE intervention) and dynamic partition pruning on BigLake tables.
I had to upgrade the client library to use the new field and had to upgrade GAX because the newer version of client libraries require newer GAX version.
Testing: Verified that DPP works on TPC-DS query 25.

Propagate stats from BigLake tables.

---

CHANGES.md
README-template.md
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClient.java
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryDirectDataWriterHelper.java
spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConfig.java
spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/BigQueryDataSourceWriterInsertableRelation.java
spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/BigQueryDataSourceWriterModule.java
spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/BigQueryDirectDataSourceWriterContext.java
spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/BigQueryDirectDataWriterContext.java
spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/write/context/BigQueryDirectDataWriterContextFactory.java
spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/integration/WriteIntegrationTestBase.java
spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/write/context/BigQueryDirectDataSourceWriterContextTest.java

to support streaming scenarios in which small batches of data are written.

Implement at-least-once option that utilizes default stream

---

spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkFilterUtils.java
spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/SparkFilterUtilsTest.java

The `spark.sql.datetime.java8API.enabled` configuration as described in https://spark.apache.org/docs/3.0.0/configuration.html is not currently handled (when set to `true`) when compiling filters. Date or timestamp literals will be `java.time.LocalDate` or `java.time.Instant` respectively and thus not properly escaped by https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/master/spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkFilterUtils.java#L318 resulting in query failures due to invalid syntax.

Handle Java 8 types for dates and timestamps when compiling filters

---

CHANGES.md
spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/direct/DirectBigQueryRelation.java

Currently Spark execution plans are rendered using the default toString implementation:
```
(3) LogicalRelation
Arguments: com.google.cloud.spark.bigquery.direct.DirectBigQueryRelation@18db53e9, [d_date_sk#516L, ...]
```
This adds a `toString()` implementation to output the actual table being read:
```
scala> res0.explain()
== Physical Plan ==
*(1) Scan DirectBigQueryRelation[anaml-dev-nonprod.tpcds_scale_1000.catalog_sales] [cs_sold_date_sk#0L,cs_sold_time_sk#1L...]
```

add toString to DirectBigQueryRelation

---

CHANGES.md
README-template.md
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryUtil.java
spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/integration/WriteIntegrationTestBase.java

Currently, we allow reading BQ's TIME datatype into Spark's long datatype. However, there's no way to write into BQ's TIME datatype.
This change adds that functionality through String.

Issue #144: allow writing Spark String to BQ TIME type

---

spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConfig.java

- The current retry settings was initialised with max attempts only, this initialises the delay between runs to 0, meaning that the 5 calls will happen with 0 millis between them and not actually an exponential retry strategy like it implies here: https://github.com/GoogleCloudDataproc/spark-bigquery-connector/blob/741bdb33bf5c06fb3fad9defffa65ea1470d2690/bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryDirectDataWriterHelper.java#L133-L142 (ran a test for the retryCallable method with the current settings and indeed the delay was 0 between calls)
- So we initialise, it with the same settings as reading (can be tuned later) as otherwise the API is hammered leading to all failures
Testing main:
```java
public static void main(String[] args) throws …
```

fix(writer): Initialise retry settings with a delay between retires

---

bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClient.java
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/ReadSessionCreator.java

Currently debug logs show up like this which is not useful:
```
23/08/29 07:01:12 DEBUG BigQueryClient: destinationTable is %s
23/08/29 07:01:12 DEBUG BigQueryClient: running query %s
23/08/29 07:01:14 DEBUG BigQueryClient: job has finished. %s
```

fix logging

---

spark-bigquery-dsv2/spark-bigquery-metrics/src/main/java/com/google/cloud/spark/bigquery/v2/customMetrics/MetricUtils.java
spark-bigquery-dsv2/spark-bigquery-metrics/src/main/java/com/google/cloud/spark/bigquery/v2/customMetrics/SparkBigQueryBytesReadMetric.java
spark-bigquery-dsv2/spark-bigquery-metrics/src/main/java/com/google/cloud/spark/bigquery/v2/customMetrics/SparkBigQueryCustomMetricConstants.java
spark-bigquery-dsv2/spark-bigquery-metrics/src/main/java/com/google/cloud/spark/bigquery/v2/customMetrics/SparkBigQueryParseTimeMetric.java
spark-bigquery-dsv2/spark-bigquery-metrics/src/main/java/com/google/cloud/spark/bigquery/v2/customMetrics/SparkBigQueryRowsReadMetric.java
spark-bigquery-dsv2/spark-bigquery-metrics/src/main/java/com/google/cloud/spark/bigquery/v2/customMetrics/SparkBigQueryScanTimeMetric.java
spark-bigquery-dsv2/spark-bigquery-metrics/src/main/java/com/google/cloud/spark/bigquery/v2/customMetrics/SparkBigQueryTimeInSparkMetric.java
spark-bigquery-dsv2/spark-bigquery-metrics/src/test/java/com/google/cloud/spark/bigquery/v2/customMetrics/SparkBigQueryBytesReadMetricTest.java
spark-bigquery-dsv2/spark-bigquery-metrics/src/test/java/com/google/cloud/spark/bigquery/v2/customMetrics/SparkBigQueryParseTimeMetricTest.java
spark-bigquery-dsv2/spark-bigquery-metrics/src/test/java/com/google/cloud/spark/bigquery/v2/customMetrics/SparkBigQueryRowsReadMetricTest.java
spark-bigquery-dsv2/spark-bigquery-metrics/src/test/java/com/google/cloud/spark/bigquery/v2/customMetrics/SparkBigQueryScanTimeMetricTest.java
spark-bigquery-dsv2/spark-bigquery-metrics/src/test/java/com/google/cloud/spark/bigquery/v2/customMetrics/SparkBigQueryTimeInSparkMetricTest.java

Format metrics; add (min, med, max) for timing metrics

---

CHANGES.md
spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SchemaConverters.java

Fix Null pointer exception when updating an existing bigquery table with NUMERIC attributes without scale and precision explicitly set

Handle NPE case when reading BQ table with NUMERIC fields

---

spark-bigquery-dsv2/spark-3.2-bigquery-lib/src/main/java/com/google/cloud/spark/bigquery/v2/Spark32BigQueryScanBuilder.java
spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/v2/context/ArrowInputPartitionContext.java
spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/v2/context/BigQueryDataSourceReaderContext.java

During Dynamic partition pruning, we currently retain the number of partitions. To reassign new (fewer) DPP partitions to the older reported partitions, we assign empty partition values to the remaining partitions.
This change resets the partitions entirely and does not attempt to retain partition numbers.

Avoid empty partitions during DPP

---

README.md

Fixing example under [**Using in Jupyter Notebooks**](https://github.com/GoogleCloudDataproc/spark-bigquery-connector#using-in-jupyter-notebooks). 
The python example was missing `\` for the multi-line statement. Also, the scala example was tagged as python language so syntax highlighting wasn't working.

add missing backslashes for multi-line python example

---

spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryUtil.java
spark-bigquery-connector-common/src/main/java/org/apache/spark/sql/Scala213SparkSqlUtils.java
spark-bigquery-scala-212-support/src/main/java/org/apache/spark/sql/PreScala213SparkSqlUtils.java

The `AttributeReference` class depends on Scala's `Seq`. As scala 2.13 has changed the Seq alias, we need to compile it's usages in different artifacts as the final bytecode  contains the aliased Seq, not `scala.Seq`. It means that if we compile using spark-sql_2.12 dependency it won't work on Scala 2.13, and vice versa.
The names of the variables were changed in order to avoid CPD errors.

Fixing the nightly build

---

CHANGES.md
spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/v2/context/BigQueryDataSourceReaderContext.java

We use pushed filters indirectly as a key in read session cache. However, it misses caching opportunities for duplicated filters and out of order filters.
This fixes that.

Improve read session caching key

---

spark-bigquery-parent/pom.xml

- Brings a fix to a retry strategy making it a bit less aggressive
- https://github.com/googleapis/java-bigquerystorage/releases/tag/v2.45.0

Upgrade bigquery storage library

---

spark-bigquery-parent/pom.xml

Pickup bugfix made to ensure the initial retry delay is respected
https://github.com/googleapis/java-bigquerystorage/releases/tag/v2.46.0

Upgrade bigquery storage library to pick up fix

---

CHANGES.md
README-template.md
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryUtil.java
spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/integration/WriteIntegrationTestBase.java

Currently, there is no way to write to a BQ datetime column from Spark <= 3.3 (Spark 3.4+ has TimestampNTZ).
This PR adds the functionality to do so by allowing String to write to datetime.

allow writing spark string to BQ datetime

---

CHANGES.md
spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkFilterUtils.java
spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/SparkFilterUtilsTest.java

Below is an example of a filter where the SQL generated is incorrect:
```
[
Or(Not(EqualNullSafe(foo, 0.0)), Not(EqualNullSafe(bar, 0.0))),
EqualNullSafe(foo, 0.0),
EqualNullSafe(bar, 0.0),
]
```
This generates the following SQL query:
```
(((NOT (`foo` IS NULL AND 0 IS NULL OR `foo` IS NOT NULL AND 0 IS NOT NULL AND `foo` = 0))) OR ((NOT (`bar` IS NULL AND 0 IS NULL OR `bar` IS NOT NULL AND 0 IS NOT NULL AND `bar` = 0)))) AND `bar` IS NULL AND 0 IS NULL OR `bar` IS NOT NULL AND 0 IS NOT NULL AND `bar` = 0 AND `foo` IS NULL AND 0 IS NULL OR `foo` IS NOT NULL AND 0 IS NOT NULL AND `foo` = 0
```
If you take a simple table as follows:
The query above returns the following results, whereas it clearly should be empty:
With this change each filter will be surrounded by `(...)`, getting you:
``` …
```

Fix filters by adding surrounding parenthesis

---

.gitignore
CHANGES.md
README-template.md
README.md
bigquery-connector-common/pom.xml
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/DecompressReadRowsResponse.java
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/ReadRowsResponseInputStreamEnumeration.java
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/ReadSessionCreator.java
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/ReadSessionCreatorConfig.java
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/ReadSessionCreatorConfigBuilder.java
bigquery-connector-common/src/test/java/com/google/cloud/bigquery/connector/common/ReadSessionCreatorTest.java
spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/ArrowBinaryIterator.java
spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/AvroBinaryIterator.java
spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/ReadRowsResponseToInternalRowIteratorConverter.java
spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConfig.java
spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/direct/BigQueryRDDContext.java
spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/SparkBigQueryConfigTest.java
spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/integration/ReadIntegrationTestBase.java
spark-bigquery-dsv1/src/test/scala/com/google/cloud/spark/bigquery/SchemaIteratorSuite.scala
spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/v2/context/ArrowColumnBatchPartitionReaderContext.java
spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/v2/context/ArrowInputPartitionContext.java
spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/main/java/com/google/cloud/spark/bigquery/v2/context/BigQueryDataSourceReaderContext.java
spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/test/java/com/google/cloud/spark/bigquery/v2/context/ArrowInputPartitionContextTest.java
spark-bigquery-dsv2/spark-bigquery-dsv2-common/src/test/java/com/google/cloud/spark/bigquery/v2/context/BigQueryInputPartitionReaderContextTest.java

This adds the ability to request compressed ReadRowsResponses.
If the server decides to give back a ReadRowsResponse, we use the specified compression algorithm (LZ4) to decompress the results. 
This also adds two integration tests to test requesting compressed results for both arrow and avro.

add option to request lz4 compressed ReadRowsResponse

---

bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryUtil.java
bigquery-connector-common/src/test/java/com/google/cloud/bigquery/connector/common/BigQueryUtilTest.java
spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/integration/ReadIntegrationTestBase.java

When getting partitioning fields, `timePartitioning.getField()` returns null when the table is ingestion time partitioned (partitioned by `_PARTITIONTIME` OR `_PARTITIONDATE`).
The change fixes this bug.

Issue #1254: fix getting partitioning fields for pseudo columns

---

spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkFilterUtils.java
spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/SparkFilterUtilsTest.java

https://github.com/GoogleCloudDataproc/spark-bigquery-connector/pull/1166 added parentheses when joining multiple filters together. There were already surrounding parentheses for `And` `Or` and `Not` filters. This updates `EqualNullSafe` to also surround the two separate `OR` clauses.
At a minimum I feel this improves the readability of the generated filters. Unsure whether, as in the other PR, there is the risk of query correctness when multiple filters are combined together?

Add additional parentheses for EqualNullSafe filter generation

---

spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryUtil.java
spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/SparkBigQueryUtilTest.java

When `spark.sql.datetime.java8API.enabled` is `true`, Spark dates and timestamps will be returned as `java.time.LocalDate`/`java.time.Instant` rather than `java.sql.Date`/`java.sql.Timestamp`. 
https://issues.apache.org/jira/browse/SPARK-38437 addressed this in https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/util/DateTimeUtils.scala so perhaps this code path could leverage that?
Currently if this config is enabled you hit `java.lang.ClassCastException`.

Support spark.sql.datetime.java8API.enabled

---

CHANGES.md
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryClient.java
cloudbuild/cloudbuild.yaml
spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/integration/WriteIntegrationTestBase.java

TableInfo.getNumRows() only covers the data that's materialized to data files, without including the data in streaming buffer. The data in streaming buffer (a.k.a, ingested through Write API, but not converted to data file yet) is readable using ReadAPI, but accessing TableInfo.getNumRows() won't reflect whatever changes are made in the streaming buffer. Running a select count(1) query works, as it triggers actual data scan through ReadAPI.
This issue only affects direct write.

Issue #1290: Stopped using metadata for optimized count path

---

CHANGES.md

Fix for #908 (`preferred_min_stream_count`) is available from version 0.30.0 of the connector and not 0.29.0 as `CHANGES.md` states. Move the entry to the proper version section to reduce confusion for users who use old versions.

Move misplaced entry in CHANGES file

---

spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/integration/OpenLineageIntegrationTestBase.java
spark-bigquery-dsv2/spark-3.1-bigquery-lib/src/main/java/com/google/cloud/spark/bigquery/v2/Spark31BigQueryTable.java
spark-bigquery-parent/pom.xml

Utilize `openlineage-spark` feature to extract lineage out of query

Get lineage out of query

---

README-template.md
bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/BigQueryUtil.java
bigquery-connector-common/src/test/java/com/google/cloud/bigquery/connector/common/BigQueryUtilTest.java
spark-bigquery-connector-common/src/main/java/com/google/cloud/spark/bigquery/SparkBigQueryConfig.java
spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/SparkBigQueryConfigTest.java
spark-bigquery-connector-common/src/test/java/com/google/cloud/spark/bigquery/integration/ReadIntegrationTestBase.java

This PR enables reading from BigQuery tables with spaces in their names by updating the table parsing logic and improving the isQuery function. It also introduces support for backticked identifiers for ambiguous table names that contain SQL keywords (e.g., orders from 2023), ensuring they are always correctly identified as table names.

Support reading from BigQuery tables with spaces in their names

---

cloudbuild/nightly.sh
cloudbuild/nightly.yaml
spark-bigquery-dsv1/spark-bigquery_2.12/pom.xml

This PR fixes the nightly build by ensuring the Scala support module is correctly included in the build artifact. And, it also temporarily removes the deploy stage to avoid failure.

Fix: Resolve nightly build and deploy failures

---

bigquery-connector-common/src/main/java/com/google/cloud/bigquery/connector/common/ReadSessionCreator.java
spark-bigquery-dsv2/spark-3.1-bigquery-lib/src/main/java/com/google/cloud/spark/bigquery/v2/Spark31BigQueryScanBuilder.java

Fix the call to get friendly name. Since BQ does not create a friendly name for a table when we use a builder to create a table, we need to use the big query util to get the friendly table name.

Fix the logging for pushdown filters
